echo "
alter database replication definition CI_HIS
with primary at SQL_CI.EXP
not replicate tables in (FMC_ACT, FMC_HIS_DER, FRN_TDP, SAD_APL, SAD_DST_FAX, SAD_DST_MAIL, SAD_ECH, SAD_EXP, SAD_FAX, SAD_MAIL, SAD_CFE, SAD_MSG_TFM, SAD_NAV, SAD_PAL, SAD_PLN, SAD_PMA, SAD_PMV, SAD_PRV, SAD_PIC, SAD_SAGA, SAD_TFM, SAD_TUB, SAD_TXT_FAX, SAD_TXT_MAIL, SAD_TXT_TFM, SAD_BAF, SAD_BAD, WEB_EVT, WEB_TXT, FMC_SYN, SYN_BAS_SEG, SYN_BOU_POR, SYN_INV_SEG, SYN_NEU_SEG, SYN_OBJ_SEG, SYN_RAB_SEG, SYN_BOU_SEG, SYN_OBJ_POR, VOI_DAI , VOI_RAD, EQT_FIL, EQT_FIL_TRV, FMC_PUR, FMC_REV, MES_NIV, MGA_MSG_PO, REF_PIT_MESSAGE)
go" | isql -Usa -Pzigramur -SREP_CI

echo "
alter database replication definition DS_HIS
with primary at SQL_DS.EXP
not replicate tables in (FMC_ACT, FMC_HIS_DER, FRN_TDP, SAD_APL, SAD_DST_FAX, SAD_DST_MAIL, SAD_ECH, SAD_EXP, SAD_FAX, SAD_MAIL, SAD_CFE, SAD_MSG_TFM, SAD_NAV, SAD_PAL, SAD_PLN, SAD_PMA, SAD_PMV, SAD_PRV, SAD_PIC, SAD_SAGA, SAD_TFM, SAD_TUB, SAD_TXT_FAX, SAD_TXT_MAIL, SAD_TXT_TFM, SAD_BAF, SAD_BAD, WEB_EVT, WEB_TXT, FMC_SYN, SYN_BAS_SEG, SYN_BOU_POR, SYN_INV_SEG, SYN_NEU_SEG, SYN_OBJ_SEG, SYN_RAB_SEG, SYN_BOU_SEG, SYN_OBJ_POR, VOI_DAI , VOI_RAD, EQT_FIL, EQT_FIL_TRV, FMC_PUR, FMC_REV, MES_NIV, MGA_MSG_PO, REF_PIT_MESSAGE)
go" | isql -Usa -Pzigramur -SREP_DS

echo "
alter database replication definition DM_HIS
with primary at SQL_DM.EXP
not replicate tables in (FMC_ACT, FMC_HIS_DER, FRN_TDP, SAD_APL, SAD_DST_FAX, SAD_DST_MAIL, SAD_ECH, SAD_EXP, SAD_FAX, SAD_MAIL, SAD_CFE, SAD_MSG_TFM, SAD_NAV, SAD_PAL, SAD_PLN, SAD_PMA, SAD_PMV, SAD_PRV, SAD_PIC, SAD_SAGA, SAD_TFM, SAD_TUB, SAD_TXT_FAX, SAD_TXT_MAIL, SAD_TXT_TFM, SAD_BAF, SAD_BAD, WEB_EVT, WEB_TXT, FMC_SYN, SYN_BAS_SEG, SYN_BOU_POR, SYN_INV_SEG, SYN_NEU_SEG, SYN_OBJ_SEG, SYN_RAB_SEG, SYN_BOU_SEG, SYN_OBJ_POR, VOI_DAI , VOI_RAD, EQT_FIL, EQT_FIL_TRV, FMC_PUR, FMC_REV, MES_NIV, MGA_MSG_PO, REF_PIT_MESSAGE)
go" | isql -Usa -Pzigramur -SREP_DM

