make_trg.sh asql_c01_res_air.trg CI
make_trg.sh asql_c02_res_aut.trg CI 
make_trg.sh asql_c03_res_cha.trg CI
make_trg.sh asql_c04_res_dis.trg CI
make_trg.sh asql_c05_res_ech.trg CI
make_trg.sh asql_c06_res_inf.trg CI
make_trg.sh asql_c07_res_itp.trg CI
make_trg.sh asql_c08_res_neu.trg CI
make_trg.sh asql_c09_res_pea.trg CI
make_trg.sh asql_c10_res_pnt.trg CI
make_trg.sh asql_c11_res_pol.trg CI
make_trg.sh asql_c12_res_por.trg CI
make_trg.sh asql_c13_res_ptl.trg CI 
make_trg.sh asql_c14_res_seg.trg CI
make_trg.sh asql_c15_res_sup.trg CI
make_trg.sh asql_c16_res_trc.trg CI
make_trg.sh asql_c17_res_trn.trg CI
make_trg.sh asql_c18_res_vil.trg CI
make_trg.sh asql_t02_fmc_his.trg CI
make_trg.sh asql_t03_fmc_rev.trg CI
make_trg.sh asql_t04_eqt_gen.trg CI
make_trg.sh asql_t06_fmc_acc.trg CI
make_trg.sh asql_t07_fmc_bas.trg CI
make_trg.sh asql_t08_fmc_cnc.trg CI
make_trg.sh asql_t09_fmc_del.trg CI
make_trg.sh asql_t10_fmc_ech.trg CI
make_trg.sh asql_t11_fmc_mnf.trg CI
make_trg.sh asql_t12_fmc_trf.trg CI
make_trg.sh asql_t13_fmc_veh.trg CI
make_trg.sh asql_t14_act_gen.trg CI
make_trg.sh asql_t15_act_int.trg CI
make_trg.sh asql_t16_act_sis.trg CI
make_trg.sh asql_t17_act_dep.trg CI
make_trg.sh asql_t18_act_rmq.trg CI
make_trg.sh asql_t19_act_frg.trg CI
make_trg.sh asql_t20_act_gar.trg CI
make_trg.sh asql_t23_alt_exp.trg CI
make_trg.sh asql_t24_mes_niv.trg CI
make_trg.sh asql_t26_eqt_gen.trg CI
