make_trg.sh asql_t02_fmc_his.trg DM
make_trg.sh asql_t03_fmc_rev.trg DM
make_trg.sh asql_t04_eqt_gen.trg DM
make_trg.sh asql_t06_fmc_acc.trg DM
make_trg.sh asql_t07_fmc_bas.trg DM
make_trg.sh asql_t08_fmc_cnc.trg DM
make_trg.sh asql_t09_fmc_del.trg DM
make_trg.sh asql_t10_fmc_ech.trg DM
make_trg.sh asql_t11_fmc_mnf.trg DM
make_trg.sh asql_t12_fmc_trf.trg DM
make_trg.sh asql_t13_fmc_veh.trg DM
make_trg.sh asql_t14_act_gen.trg DM
make_trg.sh asql_t15_act_int.trg DM
make_trg.sh asql_t16_act_sis.trg DM
make_trg.sh asql_t17_act_dep.trg DM
make_trg.sh asql_t18_act_rmq.trg DM
make_trg.sh asql_t19_act_frg.trg DM
make_trg.sh asql_t20_act_gar.trg DM
make_trg.sh asql_t22_fmc_trs.trg DM
make_trg.sh asql_t25_eqt_fil.trg DM
make_trg.sh asql_t26_eqt_gen.trg DM
