make_trg.sh asql_t02_fmc_his.trg DS
make_trg.sh asql_t03_fmc_rev.trg DS
make_trg.sh asql_t04_eqt_gen.trg DS
make_trg.sh asql_t06_fmc_acc.trg DS
make_trg.sh asql_t07_fmc_bas.trg DS
make_trg.sh asql_t08_fmc_cnc.trg DS
make_trg.sh asql_t09_fmc_del.trg DS
make_trg.sh asql_t10_fmc_ech.trg DS
make_trg.sh asql_t11_fmc_mnf.trg DS
make_trg.sh asql_t12_fmc_trf.trg DS
make_trg.sh asql_t13_fmc_veh.trg DS
make_trg.sh asql_t14_act_gen.trg DS
make_trg.sh asql_t15_act_int.trg DS
make_trg.sh asql_t16_act_sis.trg DS
make_trg.sh asql_t17_act_dep.trg DS
make_trg.sh asql_t18_act_rmq.trg DS
make_trg.sh asql_t19_act_frg.trg DS
make_trg.sh asql_t20_act_gar.trg DS
make_trg.sh asql_t22_fmc_trs.trg DS
make_trg.sh asql_t25_eqt_fil.trg DS
make_trg.sh asql_t26_eqt_gen.trg DS
