#!/bin/ksh
#################################################################################
# PROJET MIGRAZUR
#################################################################################
#
# SOUS-SYSTEME outils
#################################################################################
#
# DESCRIPTION DU SCRIPT :
# Syntaxe  : make_prc <fichier proc>[sp][.prc] <code site> [PC_SIMPL]
# Exemples : Voir ci-dessous ou lancer sans arguments#
# Genere un repertoire exec complet
#
#############################################################################
#
# Service rendu
#################################################################################

# ------------------------------------------------ 
# Variables et constantes
proc_ref="/share_podf1_home/references_dev/proc_sybase"
Nom_Prog=`basename $0`
# Nom des fichiers temporaires utilises durant la compilation de la procedure
# Repertoire des fichiers d'en-tete communs inclus
Rep_Inclus_Commun=/users/$USER/migrazur/XDMICG/inc
Fichier_Trace=$Nom_Prog.err
Fichier_log=${proc_ref}/build_prc.log
directive_compil_Plateforme=""
liv_ref="/share_podf1_home/transfert_DEV/livraisons"

# ------------------------------------------------ 
# fonctions
# ------------------------------------------------ 

echo_err ()
{
	echo ""
	echo -e '\E[47;31m'"\033[1m(`basename $0`) Erreur: $1  \033[0m"
	echo ""
	usage	
	exit 1;
}


# ------------------------------------------------ 
usage ()
{
    echo " "
    echo -e '\E[47;34m'"\033[1mla commande make_prc a ete  modifiee.\033[0m"
    echo " make_prc appelle  le script ${Nom_Prog} qui prend en compte les specificites de l'environement de developpement et celles de production."
    echo " " 
    echo " Usage    : $Nom_Prog  (<proc>|<fichier_proc>) <site>  <cible>"
    echo " les parametres:" 
    echo " <proc> : par convension nom de la procedure en minuscule "    
    echo " <fichichier_proc> : nom du fichier " 
    echo " <site> : CI | VC | DP | HIS | CA"  
    echo " <cible> : DEV| <numero_jira>"  
    echo " <numero_jira> : corespond au numero de la jira de reference correspondant a la livraison"  
    echo " "
    echo -e '\E[47;34m'"\033[1mPOUR ENVIRONEMENT DE DEVELOPPEMENT \033[0m"
    echo " make_prc appelle  le script (${Nom_Prog} ) pour prendre en compte les specificites de l'environement de developpement.(directive DEV)"
    echo " La procedure presente en base cible est sauvegardee avant le chargement d'une nouvelle procedure sur la plateforme de dev."
    echo " Cette sauvegarde se trouve sous: $proc_ref "
    echo -e '\E[47;34m'"\033[1m Exemple: procedure pour le site CI plateforme de DEV  (via make_prc): $0 xzae49 CI DEV \033[0m"

	echo " "
    echo -e '\E[47;34m'"\033[1mPOUR ENVIRONEMENT DE PRODUCTION \033[0m" 
    echo " la procedure stockee pour l'environement de production est  compilee depuis l'espace de DEV."
    echo " le livrable d'une procedure stockee devient le fichier .sql  ( anciennement .i)"
    echo " ${Nom_Prog} genere le fichier .sql a livrer en production via le script sae_liv <num_jira> -p <fichichier_proc> <site> "
    echo " pour information, la procedure présente en base cible de production est sauvegardee par le script de deployement en production."
    echo -e '\E[47;34m'"\033[1m Exemple: procedure pour le site CI en production (via sae_liv) : $0 xzae49 CI 113 \033[0m"
    echo " "


}

# ------------------------------------------------ 
# main
# ------------------------------------------------ 

# Verifier la presence et la validite des arguments obligatoires
if [[ $# -ne 3 ]]; then
	echo_err "Manque des paramettres nom proc : $1 site de compil $1 cible $3 "
	exit 1
fi

Fichier_Proc_Arg=$1
typeset -u Site_Compil=$2
cible=$3

directive_compil_Plateforme=""


# Verifier l'existence du fichier source de la procedure
if [[ -r ${Fichier_Proc_Arg} ]]
then
	Fichier_Proc=${Fichier_Proc_Arg}

elif [[ -r ${Fichier_Proc_Arg}.prc ]]
then
	Fichier_Proc=${Fichier_Proc_Arg}.prc

elif [[ -r ${Fichier_Proc_Arg}sp.prc ]]
then
	Fichier_Proc=${Fichier_Proc_Arg}sp.prc
else
	echo "*** $Nom_Prog : Le fichier '$Fichier_Proc_Arg' est introuvable"  >&2
	exit 2
fi

# recuperation du nom de la procedure dans le fichier
nom_procedure_reel=`cat $Fichier_Proc | grep "create procedure" | awk  '{ print $3 }'`
if ( grep -sq ";" <<< $nom_procedure_reel ) 
then 
    echo_err "cette procedure est groupe $nom_procedure_reel elle ne peut etre compilee avec $0 "
fi

# Determiner les options de compilation Si DEV ou PROD
case $cible in
    "DEV" ) # cette directive permet de bouchonner les equipements
    directive_compil_Plateforme="-DDEV"
    ;;

    *)  # pas de directive particuliere pour la prod en revanche nous devons connaitre le numero de la jira
        directive_compil_Plateforme=""
        # ces controle on deja ete faiten amont     
		if ! [[ $cible =~ ^[0-9]+$ ]]
		then
		   echo_err  "le parametre $cible doit corespondre au numero de la Jira qui porte la demande de modification (DEM)" 
          
 		fi
		liv_ref_complet="$liv_ref/SAE_$cible/proc"
   
    ;;
esac ;

# Determiner les options de compilation en fonction du serveur
case $Site_Compil in
    "HIS" )
    Option_Serveur="HIST"
    ;;
    "CI" )
    Option_Serveur=$Site_Compil
    ;;
    "CA" )
    Option_Serveur="$Site_Compil  -DCI"
    ;;

    *)
    Option_Serveur="PC2"    # cette directive n'existe plus dans le code (comme PC_SIMP)" elle pourait être utile pour du code conditionne sur les secteurs
    ;;
esac ;


Nom_Fic_Source=$Fichier_Proc

# Initialiser le fichier de trace des erreurs
{
	echo "____________________________________________________________________________________________________"
	echo ""
	date +'%d/%m/%Y %H:%M:%S'
	echo "Compilation sur le serveur $Site_Compil du fichier de procedure stockee :"
	echo "${Fichier_Proc}"
	echo ""
} >> $Fichier_Trace


if [[ -r ${Nom_Fic_Source}.c ]]
then
	rm ${Nom_Fic_Source}.c
fi


# verification  que la procedure contient le drop procedure
# l'option q meconnue permet depa faire l'affichage
# si il y est pas il faut le raroute
if ! ( grep -sq "drop proc"  ${Nom_Fic_Source} ) 
then 
    echo "Attention : pas de drop dans cette procedure ${Nom_Fic_Source} "
    echo "un drop de la procedure est rajoute dans la precompil du fichier ${Nom_Fic_Source} "
    # on rajoute systematiquement sa suppression
    echo "use PRC" >  ${Nom_Fic_Source}.c
    echo "go" >> ${Nom_Fic_Source}.c
    echo "if exists (select 1 from sysobjects where name = '${nom_procedure_reel}' and type = 'P')" >> ${Nom_Fic_Source}.c
    echo "  drop procedure ${nom_procedure_reel}" >> ${Nom_Fic_Source}.c
    echo "go" >> ${Nom_Fic_Source}.c
fi
# Initialiser le fichier source avec les inclusions de fichiers d'en-tete
{
	echo "#include \"$Rep_Inclus_Commun/xdc.h\""
	echo "#include \"$Rep_Inclus_Commun/xzaec.h\""
}  >> ${Nom_Fic_Source}.c

case "$Fichier_Proc" in
    xza* )
	# Determiner la famille de la procedure (donnee par les 4 premieres lettres du nom)
	Famille_Proc=${Fichier_Proc:0:4}

	# Inclure les en-tetes suivants quelle que soit la famille de la procedure
	{
		echo "#include \"$Rep_Inclus_Commun/xzaac.h\""
		echo "#include \"$Rep_Inclus_Commun/xzacc.h\""
		echo "#include \"$Rep_Inclus_Commun/xzahc.h\""
	}  >> ${Nom_Fic_Source}.c

	# Pour les autres familles, inclure l'en-tete des constantes de la famille s'il existe
	case "$Famille_Proc" in
	    xzaa | xzac | xzae | xzah )
		;;

	    * )
		if [[ -r "$Rep_Inclus_Commun/${Famille_Proc}c.h" ]]; then
			echo "#include \"$Rep_Inclus_Commun/${Famille_Proc}c.h\"" >> ${Nom_Fic_Source}.c
		fi
	esac
esac


# Ajouter le code source de la procedure elle-meme
cat $Fichier_Proc >> ${Nom_Fic_Source}.c

# 


# # Passer le preprocesseur C sur le code de la procedure puis l'executer sur le site indique

if [ "$cible" != "DEV" ]
then
    echo "  cc -E -P -C ${directive_compil_Plateforme} -D${Option_Serveur} ${Nom_Fic_Source}.c  > ${liv_ref_complet}/${Site_Compil}_${Nom_Fic_Source}.sql"    
    cc -E -P -C ${directive_compil_Plateforme} -D${Option_Serveur} ${Nom_Fic_Source}.c  > ${liv_ref_complet}/${Site_Compil}_${Nom_Fic_Source}.sql

else   # cas de la plateforme de dev, on effectue  les mêmes opération qu'avant
echo "cc -E -P -C ${directive_compil_Plateforme}  -D${Option_Serveur} ${Nom_Fic_Source}.c  > ${Site_Compil}_${Nom_Fic_Source}.sql"

    cc -E -P -C ${directive_compil_Plateforme} -D${Option_Serveur} ${Nom_Fic_Source}.c  > ${Site_Compil}_${Nom_Fic_Source}.sql
    # Sauvegarde  la proc en base
    date_backup=`date +'%d%m%Y_%H%M%S'`
    fichier_sauvegarde="$proc_ref/${Site_Compil}_${Nom_Fic_Source}.${date_backup}"
    echo "Sauvegarde de la procedure ${nom_procedure_reel} en base ${Site_Compil} ..."
    echo "dans le fichier ${fichier_sauvegarde}"
    {
        echo "use PRC"
        echo "go"
        echo "sp_showtext $nom_procedure_reel "
        echo "go"
        } | isql -Usa -Pzigramur -w2000 -SSQL_${Site_Compil}  -Jiso_1   >  $proc_ref/${Site_Compil}_${Nom_Fic_Source}.svg


    echo "use PRC" >  ${fichier_sauvegarde}
    echo "go" >> ${fichier_sauvegarde}
    echo "if exists (select 1 from sysobjects where name = '${nom_procedure_reel}' and type = 'P')" >> ${fichier_sauvegarde}
    echo "  drop procedure ${nom_procedure_reel}" >> ${fichier_sauvegarde}
    echo "go" >> ${fichier_sauvegarde}
    cat "$proc_ref/${Site_Compil}_${Nom_Fic_Source}.svg" >> ${fichier_sauvegarde}
    echo "go" >> ${fichier_sauvegarde}
    chmod 775 ${fichier_sauvegarde}   # on donne les droits au groupe
    
    echo "Compilation de procedure sur le site ${Site_Compil} en cours ..."
     isql -UMIGRAZUR -PMIGRAZUR  -SSQL_${Site_Compil}  -i ${Site_Compil}_${Nom_Fic_Source}.sql  2>&1  | tee -a $Fichier_Trace 

    # Supprimer les fichiers intermediaires
     rm ${Nom_Fic_Source}.c ${Site_Compil}_${Nom_Fic_Source}.sql $proc_ref/${Site_Compil}_${Nom_Fic_Source}.svg
fi

# fichier log centralisé des procedures stockees
echo "`date +'%d/%m/%Y %H:%M:%S'`$USER ${Nom_Prog} cible SAE_$cible : Compilation sur $Site_Compil de la procedure stockee : ${Fichier_Proc}"  >> $Fichier_log
