/* Fichier : $Id: dico.bas,v 1.4 1998/01/20 17:41:59 gaborit Exp $      Release : $Revision: 1.4 $        Date : $Date: 1998/01/20 17:41:59 $
------------------------------------------------------
* STERIA *  PROJET MIGRAZUR 
------------------------------------------------------
* SOUS-SYSTEME  BASEDD
------------------------------------------------------
* FICHIER dico.bas
------------------------------------------------------
* DESCRIPTION DE LA PROCEDURE :
*
* Initialisation de la table des libelles predefinis
*
------------------------------------------------------
* HISTORIQUE :
*
* L.V.  21/08/96: Creation
* C.T.  16/01/98: ajout libelle sur PAL,FAU, FAC (1538) (1.4)
-----------------------------------------------------*/


use VUE
go

insert DICO (notyp, libtyp, code, libelle, explication)
values( 9, "Type d'action            ", 13, "Appel interlocuteur", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 9, "Type d'action            ", 1, "BRA", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 9, "Type d'action            ", 2, "PMV", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 9, "Type d'action            ", 3, "Signalisation tunnel", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 9, "Type d'action            ", 4, "Dépanneur", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 9, "Type d'action            ", 5, "Affichage en gare", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 9, "Type d'action            ", 6, "Patrouille SIS", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 9, "Type d'action            ", 7, "Intervention", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 9, "Type d'action            ", 8, "PMV sur remorque", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 9, "Type d'action            ", 9, "PMV sur fourgon", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 9, "Type d'action            ", 10, "Message trafic FM", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 9, "Type d'action            ", 11, "Echangeur", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 9, "Type d'action            ", 12, "Envoi fax", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 9, "Type d'action            ", 14, "Appel bip", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 9, "Type d'action            ", 43, "Fermeture d'acces", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 9, "Type d'action            ", 44, "Fermeture d'autoroute", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 9, "Type d'action            ", 45, "Panneau d'alerte", "")


insert DICO (notyp, libtyp, code, libelle, explication)
values( 11, "Type d'intervenant      ", 1, "pompiers", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 11, "Type d'intervenant      ", 2, "gendarmerie", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 11, "Type d'intervenant      ", 3, "patrouille", "")


insert DICO (notyp, libtyp, code, libelle, explication)
values( 12, "Qualification alerte    ", 0, "inconnue", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 12, "Qualification alerte    ", 1, "fausse", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 12, "Qualification alerte    ", 2, "exploitation", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 12, "Qualification alerte    ", 3, "vraie sans creation evt", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 12, "Qualification alerte    ", 4, "a confirmer avec creation evt", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 12, "Qualification alerte    ", 10, "vraie avec creation evt", "")


insert DICO (notyp, libtyp, code, libelle, explication)
values( 13, "Type de bip             ", 0, "", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 13, "Type de bip             ", 1, "Eurosignal", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 13, "Type de bip             ", 2, "Operator 80 car.", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 13, "Type de bip             ", 3, "Operator 10 chiffres", "")


insert DICO (notyp, libtyp, code, libelle, explication)
values( 14, "Type de neutralisation  ", 0, "Inconnue", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 14, "Type de neutralisation  ", 1, "Sens normal", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 14, "Type de neutralisation  ", 2, "Sens inversé", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 14, "Type de neutralisation  ", 3, "Bloquée", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 14, "Type de neutralisation  ", 4, "Inexistante", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 14, "Type de neutralisation  ", 5, "Neutralisée", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 14, "Type de neutralisation  ", 6, "Bloquée neutralisée", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 14, "Type de neutralisation  ", 7, "BAU normale", "")


insert DICO (notyp, libtyp, code, libelle, explication)
values( 15, "Type de bouchon         ", 1, "Dense", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 15, "Type de bouchon         ", 2, "Ralenti", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 15, "Type de bouchon         ", 3, "Bouche", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 15, "Type de bouchon         ", 4, "Bloque", "")



insert DICO (notyp, libtyp, code, libelle, explication)
values( 16, "Classes de FMC          ", 0, "Classe Accident", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 16, "Classes de FMC          ", 1, "Classe Delestage", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 16, "Classes de FMC          ", 2, "Classe Vehicule", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 16, "Classes de FMC          ", 3, "Classe Vehicule Lent", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 16, "Classes de FMC          ", 4, "Classe Meteo", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 16, "Classes de FMC          ", 5, "Classe Echangeur", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 16, "Classes de FMC          ", 6, "Classe Sous Concession", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 16, "Classes de FMC          ", 7, "Classe Manifestation", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 16, "Classes de FMC          ", 8, "Classe Bouchon", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 16, "Classes de FMC          ", 9, "Classe Travaux", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 16, "Classes de FMC          ", 10, "Classe Basculement", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 16, "Classes de FMC          ", 11, "Classe Poste operateur", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 16, "Classes de FMC          ", 12, "Classe Generique", "")


insert DICO (notyp, libtyp, code, libelle, explication)
values( 17, "Sens pour localisation  ", 0, "Non précisé", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 17, "Sens pour localisation  ", 1, "1", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 17, "Sens pour localisation  ", 2, "2", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 17, "Sens pour localisation  ", 3, "1, bretelle de sortie", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 17, "Sens pour localisation  ", 4, "2, bretelle de sortie", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 17, "Sens pour localisation  ", 7, "1, bretelle d'entree", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 17, "Sens pour localisation  ", 8, "2, bretelle d'entree", "")


insert DICO (notyp, libtyp, code, libelle, explication)
values( 18, "Type point caracteristiq", 11, "Aire", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 18, "Type point caracteristiq", 1, "Echangeur", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 18, "Type point caracteristiq", 2, "Peage", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 18, "Type point caracteristiq", 10, "Lit d'arret", "")


insert DICO (notyp, libtyp, code, libelle, explication)
values( 19, "Position aire/echangeur ", 0, "", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 19, "Position aire/echangeur ", 1, "Intersection avec section courante", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 19, "Position aire/echangeur ", 2, "Barrière de péage (si elle existe)", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 19, "Position aire/echangeur ", 3, "Limite de concession", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 19, "Position aire/echangeur ", 4, "Entre section courante et péage", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 19, "Position aire/echangeur ", 5, "Entre péage et limite de concession", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 19, "Position aire/echangeur ", 6, "Entre section courante et limite de conces.", "")


insert DICO (notyp, libtyp, code, libelle, explication)
values( 20, "Type de perturbation    ", 76, "chute de neige", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 20, "Type de perturbation    ", 77, "chaussée enneigée", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 20, "Type de perturbation    ", 78, "pluie", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 20, "Type de perturbation    ", 79, "vent fort", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 20, "Type de perturbation    ", 80, "brouillard", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 20, "Type de perturbation    ", 81, "brouillard et givre", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 20, "Type de perturbation    ", 82, "grele", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 20, "Type de perturbation    ", 83, "verglas", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 20, "Type de perturbation    ", 84, "autre", "")


insert DICO (notyp, libtyp, code, libelle, explication)
values( 21, "Type de travaux         ", 1, "glissières", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 21, "Type de travaux         ", 2, "végétation", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 21, "Type de travaux         ", 3, "ouvrage hydrolique", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 21, "Type de travaux         ", 4, "ouvrage d'art", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 21, "Type de travaux         ", 5, "chaussée et terrassement", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 21, "Type de travaux         ", 6, "signalisation verticale", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 21, "Type de travaux         ", 7, "signalisation horizontale", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 21, "Type de travaux         ", 8, "éclairage", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 21, "Type de travaux         ", 9, "réseau d'appel d'urgence", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 21, "Type de travaux         ", 10, "lavage, balayage tunnel", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 21, "Type de travaux         ", 11, "lavage balayage", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 21, "Type de travaux         ", 12, "maintenance d'équipement de tunnel", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 21, "Type de travaux         ", 13, "maintenance d'équipement autre que tunnel", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 21, "Type de travaux         ", 14, "élargissement", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 21, "Type de travaux         ", 15, "mur anti-bruit", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 21, "Type de travaux         ", 16, "conformité de glissière", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 21, "Type de travaux         ", 17, "autres travaux", "")


insert DICO (notyp, libtyp, code, libelle, explication)
values( 22, "Nature des travaux      ", 1, "Neufs", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 22, "Nature des travaux      ", 0, "Entretien", "")


insert DICO (notyp, libtyp, code, libelle, explication)
values( 1, "VEHICULE/categories      ", 1, "poids lourd", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 1, "VEHICULE/categories      ", 2, "véhicule léger", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 1, "VEHICULE/categories      ", 3, "car", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 1, "VEHICULE/categories      ", 4, "moto", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 1, "VEHICULE/categories      ", 5, "remorque", "")


insert DICO (notyp, libtyp, code, libelle, explication)
values( 23, "Type d equipement       ", 1, "BRA", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 23, "Type d equipement       ", 2, "PMV", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 23, "Type d equipement       ", 3, "TUBE", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 23, "Type d equipement       ", 4, "DAI", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 23, "Type d equipement       ", 5, "Systeme video", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 23, "Type d equipement       ", 6, "LT video", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 23, "Type d equipement       ", 7, "Camera", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 23, "Type d equipement       ", 8, "MAA", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 23, "Type d equipement       ", 9, "Moniteur", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 23, "Type d equipement       ", 28, "Magnetoscope", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 23, "Type d equipement       ", 11, "Demi Echangeur", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 23, "Type d equipement       ", 12, "PIRAU", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 23, "Type d equipement       ", 13, "Machine", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 23, "Type d equipement       ", 14, "PAU", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 23, "Type d equipement       ", 15, "GTC NICE", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 23, "Type d equipement       ", 18, "Capteur Tunnel", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 23, "Type d equipement       ", 19, "Feux d'affectation de voies", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 23, "Type d equipement       ", 20, "Panneau GTC", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 23, "Type d equipement       ", 21, "Module NAV", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 23, "Type d equipement       ", 22, "Serveur de terminaux", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 23, "Type d equipement       ", 23, "Mini GTC", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 23, "Type d equipement       ", 24, "Entree TOR", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 23, "Type d equipement       ", 25, "Picto", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 23, "Type d equipement       ", 26, "RADT", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 23, "Type d equipement       ", 27, "Analyseur", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 23, "Type d equipement       ", 10, "Lit d'arret", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 23, "Type d equipement       ", 29, "Extincteur", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 23, "Type d equipement       ", 30, "Capteur taux CO", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 23, "Type d equipement       ", 31, "Capteur Opacite", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 23, "Type d equipement       ", 32, "OPERATOR", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 23, "Type d equipement       ", 33, "SATIR", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 23, "Type d equipement       ", 34, "FAX", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 23, "Type d'equipement       ", 43, "Fermeture d'acces", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 23, "Type d'equipement       ", 44, "Fermeture d'autoroute", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 23, "Type d'equipement       ", 45, "Panneau d'alerte", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 23, "Type d equipement       ", 0, "Tous equipements", "")

insert DICO (notyp, libtyp, code, libelle, explication)
values( 24, "Type de reseau transver.", 1, "eau", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 24, "Type de reseau transver.", 2, "basse tension", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 24, "Type de reseau transver.", 3, "moyenne tension", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 24, "Type de reseau transver.", 4, "haute tension", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 24, "Type de reseau transver.", 5, "tres haute tension", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 24, "Type de reseau transver.", 6, "gaz", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 24, "Type de reseau transver.", 7, "autre", "")
insert DICO (notyp, libtyp, code, libelle, explication)
values( 24, "Type de reseau transver.", 8, "passage inferieur", "")

go
