/*X  Fichier : $Id: libelle_predef.bas,v 1.5 1998/01/20 17:41:50 gaborit Exp $      Release : $Revision: 1.5 $        Date : $Date: 1998/01/20 17:41:50 $
------------------------------------------------------
* STERIA *  PROJET MIGRAZUR 
------------------------------------------------------
* SOUS-SYSTEME  BASEDD
------------------------------------------------------
* FICHIER libelles.bas
------------------------------------------------------
* DESCRIPTION DE LA PROCEDURE :
*
* Initialisation de la table des libelles predefinis
*
------------------------------------------------------
* HISTORIQUE :
*
* P.V.  16/08/96: Creation
* C.T.  28/11/96: Modif type FMC et ajout nouveaux libelles (1.2 a 1.4)
* C.T.  16/01/98: Ajout nouveaux libelles FAV FAU PAL (1538) (1.5)
-----------------------------------------------------*/


use CFG
go

insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 9, 13, 1, "Appel interlocuteur", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 9, 1, 2, "BRA", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 9, 2, 3, "PMV", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 9, 3, 4, "Signalisation tunnel", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 9, 4, 5, "Dépanneur", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 9, 5, 6, "Affichage en gare", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 9, 6, 7, "Patrouille SIS", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 9, 7, 8, "Intervention", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 9, 8, 9, "PMV sur remorque", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 9, 9, 10, "PMV sur fourgon", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 9, 10, 11, "Message trafic FM", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 9, 11, 12, "Echangeur", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 9, 12, 13, "Envoi fax", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 9, 14, 14, "Appel bip", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 9, 15, 43, "Fermeture d'acces", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 9, 16, 44, "Fermeture d'autoroute", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 9, 17, 45, "Panneau d'alerte", "", 1)


insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 11, 1, 1, "pompiers", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 11, 2, 2, "gendarmerie", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 11, 3, 3, "patrouille", "", 1)


insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 12, 0, 1, "inconnue", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 12, 1, 2, "fausse", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 12, 2, 3, "exploitation", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 12, 3, 4, "vraie sans creation evt", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 12, 4, 5, "a confirmer avec creation evt", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 12, 10, 6, "vraie avec creation evt", "", 1)


insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 13, 0, 1, "", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 13, 1, 2, "Eurosignal", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 13, 2, 3, "Operator 80 car.", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 13, 3, 4, "Operator 10 chiffres", "", 1)


insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 14, 0, 1, "Inconnue", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 14, 1, 2, "Sens normal", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 14, 2, 3, "Sens inversé", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 14, 3, 4, "Bloquée", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 14, 4, 5, "Inexistante", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 14, 5, 6, "Neutralisée", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 14, 6, 7, "Bloquée neutralisée", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 14, 7, 8, "BAU normale", "", 1)


insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 15, 1, 1, "Dense", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 15, 2, 2, "Ralenti", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 15, 3, 3, "Bouche", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 15, 4, 4, "Bloque", "", 1)



insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 16, 0, 1, "Classe Accident", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 16, 1, 2, "Classe Delestage", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 16, 2, 3, "Classe Vehicule", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 16, 3, 4, "Classe Vehicule Lent", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 16, 4, 5, "Classe Meteo", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 16, 5, 6, "Classe Echangeur", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 16, 6, 7, "Classe Sous Concession", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 16, 7, 8, "Classe Manifestation", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 16, 8, 9, "Classe Bouchon", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 16, 9, 10, "Classe Travaux", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 16, 10, 11, "Classe Basculement", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 16, 11, 12, "Classe Poste operateur", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 16, 12, 13, "Classe Generique", "", 1)


insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 17, 0, 1, "Non précisé", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 17, 1, 2, "1", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 17, 2, 3, "2", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 17, 3, 4, "1, bretelle de sortie", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 17, 4, 5, "2, bretelle de sortie", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 17, 7, 6, "1, bretelle d'entree", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 17, 8, 7, "2, bretelle d'entree", "", 1)


insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 18, 0, 1, "Section courante", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 18, 11, 2, "Aire", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 18, 1, 3, "Echangeur", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 18, 2, 4, "Peage", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 18, 10, 5, "Lit d'arret", "", 1)


insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 19, 0, 1, "", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 19, 1, 2, "Intersection avec section courante", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 19, 2, 3, "Barrière de péage (si elle existe)", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 19, 3, 4, "Limite de concession", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 19, 4, 5, "Entre section courante et péage", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 19, 5, 6, "Entre péage et limite de concession", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 19, 6, 7, "Entre section courante et limite de conces.", "", 1)


insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 20, 76, 1, "chute de neige", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 20, 77, 2, "chaussée enneigée", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 20, 78, 3, "pluie", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 20, 79, 4, "vent fort", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 20, 80, 5, "brouillard", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 20, 81, 6, "brouillard et givre", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 20, 82, 7, "grele", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 20, 83, 8, "verglas", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 20, 84, 9, "autre", "", 1)


insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 21, 1, 1, "glissières", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 21, 2, 2, "végétation", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 21, 3, 3, "ouvrage hydrolique", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 21, 4, 4, "ouvrage d'art", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 21, 5, 5, "chaussée et terrassement", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 21, 6, 6, "signalisation verticale", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 21, 7, 7, "signalisation horizontale", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 21, 8, 8, "éclairage", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 21, 9, 9, "réseau d'appel d'urgence", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 21, 10, 10, "lavage, balayage tunnel", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 21, 11, 11, "lavage balayage", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 21, 12, 12, "maintenance d'équipement de tunnel", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 21, 13, 13, "maintenance d'équipement autre que tunnel", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 21, 14, 14, "élargissement", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 21, 15, 15, "mur anti-bruit", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 21, 16, 16, "conformité de glissière", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 21, 17, 17, "autres travaux", "", 1)


insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 22, 1, 1, "Neufs", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 22, 0, 2, "Entretien", "", 1)


insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 1, 1, 1, "poids lourd", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 1, 2, 2, "véhicule léger", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 1, 3, 3, "car", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 1, 4, 4, "moto", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 1, 5, 5, "remorque", "", 1)


insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 23, 1, 1, "BRA", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 23, 2, 2, "PMV", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 23, 3, 3, "TUBE", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 23, 4, 4, "DAI", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 23, 5, 5, "Systeme video", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 23, 6, 6, "LT video", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 23, 7, 7, "Camera", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 23, 8, 8, "MAA", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 23, 9, 9, "Moniteur", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 23, 28, 10, "Magnetoscope", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 23, 11, 11, "Demi Echangeur", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 23, 12, 12, "PIRAU", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 23, 13, 13, "Machine", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 23, 14, 14, "PAU", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 23, 15, 15, "GTC NICE", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 23, 18, 16, "Capteur Tunnel", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 23, 19, 17, "Feux d'affectation de voies", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 23, 20, 18, "Panneau GTC", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 23, 21, 19, "Module NAV", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 23, 22, 20, "Serveur de terminaux", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 23, 23, 21, "Mini GTC", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 23, 24, 22, "Entree TOR", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 23, 25, 23, "Picto", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 23, 26, 24, "RADT", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 23, 27, 25, "Analyseur", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 23, 10, 26, "Lit d'arret", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 23, 29, 27, "Extincteur", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 23, 30, 28, "Capteur taux CO", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 23, 31, 29, "Capteur Opacite", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 23, 32, 30, "OPERATOR", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 23, 33, 31, "SATIR", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 23, 34, 32, "FAX", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 23, 43, 33, "Fermeture d'acces", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 23, 44, 34, "Fermeture d'autoroute", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 23, 45, 35, "Panneau d'alerte", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 23, 0, 33, "Tous equipements", "", 1)

insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 24, 1, 1, "Classe de silhouettes 1", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 24, 2, 2, "Classe de silhouettes 2", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 24, 3, 3, "Classe de silhouettes 3", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 24, 4, 4, "Classe de silhouettes 4", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 24, 5, 5, "Classe de silhouettes 5", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 24, 6, 6, "Classe de silhouettes 6", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 24, 7, 7, "Classe de silhouettes 7", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 24, 8, 8, "Classe de silhouettes 8", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 24, 9, 9, "Classe de silhouettes 9", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 24, 10, 10, "Classe de silhouettes 10", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 24, 11, 11, "Classe de silhouettes 11", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 24, 12, 12, "Classe de silhouettes 12", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 24, 13, 13, "Classe de silhouettes 13", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 24, 14, 14, "Classe de silhouettes 14", "", 1)

insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 25, 1, 1, "Classe de poids d'essieux 1", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 25, 2, 2, "Classe de poids d'essieux 2", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 25, 3, 3, "Classe de poids d'essieux 3", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 25, 4, 4, "Classe de poids d'essieux 4", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 25, 5, 5, "Classe de poids d'essieux 5", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 25, 6, 6, "Classe de poids d'essieux 6", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 25, 7, 7, "Classe de poids d'essieux 7", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 25, 8, 8, "Classe de poids d'essieux 8", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 25, 9, 9, "Classe de poids d'essieux 9", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 25, 10, 10, "Classe de poids d'essieux 10", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 25, 11, 11, "Classe de poids d'essieux 11", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 25, 12, 12, "Classe de poids d'essieux 12", "", 1)

insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 26, 1, 1, "Poids 1", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 26, 2, 2, "Poids 2", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 26, 3, 3, "Poids 3", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 26, 4, 4, "Poids 4", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 26, 5, 5, "Poids 5", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 26, 6, 6, "Poids 6", "", 1)

insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 27, 1, 1, "TARIFS ESCOTA", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 27, 2, 2, "TARIFS AUTRES AUTOROUTES", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 27, 3, 3, "TEMPS PARCOURS, DISTANCES", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 27, 4, 4, "ITINERAIRES", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 27, 5, 5, "ADRESSES, TEL. ESCOTA", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 27, 6, 6, "ADRESSES, TEL. SOCIETES", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 27, 7, 7, "CLASSES TARIFAIRES", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 27, 11, 11, "CONVOIS EXCEPTIONNELS", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 27, 12, 12, "HAUTEURS SOUS OUVRAGE", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 27, 13, 13, "AUTRES", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 27, 9, 9, "METEO", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 27, 10, 10, "COND. CIRCULATION", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 27, 8, 8, "ABONNEMENTS", "", 1)

insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 28, 1, 1, "ACCIDENT", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 28, 2, 2, "Délestage", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 28, 3, 3, "Déviation", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 28, 4, 4, "Poste Opérateur", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 28, 5, 5, "PERTURBATION METEO", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 28, 6, 6, "VEHICULE A CONTRESENS", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 28, 7, 7, "VEHICULE ARRETE", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 28, 8, 8, "VEHICULE EN PANNE", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 28, 9, 9, "VEHICULE EN FEU", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 28, 10, 10, "CIRQUE EN CONVOI", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 28, 11, 11, "Convoi exceptionnel", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 28, 12, 12, "Convoi militaire", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 28, 13, 13, "VEHICULE LENT", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 28, 14, 14, "MANIFESTATION", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 28, 15, 15, "GREVE PERSONNEL ESCOTA", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 28, 16, 16, "OPERATION ESCARGOT", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 28, 17, 17, "Basculement", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 28, 18, 18, "Travaux", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 28, 19, 19, "INCIDENT SS CONCESS.", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 28, 20, 20, "BOUCHON", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 28, 21, 21, "Fermeture échangeur", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 28, 22, 22, "EBOULEMENT", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 28, 23, 23, "INCENDIE DE VEGETATION", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 28, 24, 24, "INONDATION", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 28, 25, 25, "OBSTACLE SUR CHAUSSEE", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 28, 26, 26, "CHAUSSEE DETERIOREE", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 28, 27, 27, "FLAQUE D'HUILE", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 28, 28, 28, "ANIMAL ERRANT", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 28, 29, 29, "FRONTIERE FERMEE", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 28, 30, 30, "ALTERCATION USAGERS", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 28, 31, 31, "AGRESSION", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 28, 32, 32, "MALAISE USAGER", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 28, 33, 33, "EVENEMENT HORS RESEAU", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 28, 34, 34, "Aire fermée", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 28, 35, 35, "Salage", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 28, 36, 36, "HOLD-UP / VOL", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 28, 37, 37, "BOUCHON (tête)", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 28, 38, 38, "PIETONS SUR LA CHAUSSEE", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 28, 39, 39, "AUTRE EVENEMENT", "", 1)

insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 29, 1, 1, "faible", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 29, 2, 2, "moyenne", "", 1)
insert LIB_PRE (notyp, code, position, libelle, explication, valide)
values( 29, 3, 3, "forte", "", 1)
go
