/*E Fichier : $Id: xzah_utils.h,v 1.9 2013/01/25 10:12:07 pc2dpdy Exp $      Release : $Revision: 1.9 $        Date : $Date: 2013/01/25 10:12:07 $
------------------------------------------------------
* STERIA *  PROJET MIGRAZUR
------------------------------------------------------
* SOUS-SYSTEME BASEDD
------------------------------------------------------
* MODULE XZAH_UTIL * FICHIER XZAH_UTIL.h
------------------------------------------------------
* DESCRIPTION DU MODULE :
*	Ce fichier contient des utilitaires pour les xzah**.c
*
*	XZAH_Conv_xzahcxzaec_xdc : Effectue la conversion des constantes de BASEDD 
* (contenus dans xzahc.h et xzaec.h vers les constantes de xdc.h)
* vers les constantes des autres sous systemes (XDC.h).
*
------------------------------------------------------
* HISTORIQUE :
*
* mercier	26 Oct 1994	: Creation
* torregrossa	30 Mar 1995	: Remplace la fonction par un 
*                                 tableau de correspondance (V 1.2)
* torregrossa	31 Mar 1995	: Correction erreur tableau (V 1.3)
* torregrossa	05 Avr 1995	: Ajout des objets meteo et 
*                                 intervention autre (V 1.4)
* niepceron     04 Mai 1999	: Ajout objet manquants v1.5
* Hilmarcher    22/04/05	: ajout objet grele sur la chaussee DEM456 v1.6
* JPL		23/04/07	: ajout objets Vehicule en Marche Arriere, Traitement chaussees,
*                                 Ech. deconseille, Chaussee Glissante (DEM 643-646) 1.7
* JPL		02/09/10	: Ajout objet Zone de stockage (DEM 942) 1.8
* JMG		09/01/13	: ajout FMC regulation 1.9
------------------------------------------------------ */


/* fichiers inclus */
	/* Include Sybase */

	/* Include applicatif Migrazur */
	#include "xdy.h"
	#include "xdc.h"

/* definitions de constantes exportees */

/* definitions de types exportes */

/* definition de macro exportees */

/* declarations de donnees globales */

/*A conversion des types d'objets mobiles retournes par la base */
/*A en type pour synoptiques */
static short XZAHC_ConvTypesMob[256] = { 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_FMC_DELESTAGE, 
	XDC_SYN_FMC_DEVIATION, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_FMC_VEHICULE_CONTRE_SENS,/* XZAHC_ConvTypesMob[XZAEC_FMC_Contresens=6] */
	XDC_SYN_FMC_VEHICULE_ARRETE, 	/* XZAHC_ConvTypesMob[XZAEC_FMC_VehArrete=7] */
	XDC_SYN_FMC_VEHICULE_PANNE, 	/* XZAHC_ConvTypesMob[XZAEC_FMC_VehPanne=8] */
	XDC_SYN_FMC_VEHICULE_FEU, 	/* XZAHC_ConvTypesMob[XZAEC_FMC_VehFeu=9] */
	XDC_SYN_FMC_CIRQUE, 		/* XZAHC_ConvTypesMob[XZAEC_FMC_Cirque=10] */
	XDC_SYN_FMC_CONVOI_EXCEPTIONNEL,/* XZAHC_ConvTypesMob[XZAEC_FMC_ConvoiExc=11] */
	XDC_SYN_FMC_CONVOI_MILITAIRE, 	/* XZAHC_ConvTypesMob[XZAEC_FMC_ConvoiMil=12] */
	XDC_SYN_FMC_VEHICULE_LENT, 	/* XZAHC_ConvTypesMob[XZAEC_FMC_VehLent=13] */
	XDC_SYN_FMC_MANIFESTATION, 	/* XZAHC_ConvTypesMob[XZAEC_FMC_Manifestation=14] */
	XDC_SYN_FMC_GREVE_ESCOTA, 	/* XZAHC_ConvTypesMob[XZAEC_FMC_GreveESCOTA=15] */
	XDC_SYN_FMC_OPERATION_ESCARGOT, /* XZAHC_ConvTypesMob[XZAEC_FMC_Escargot=16] */
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_FMC_INCIDENT_SOUS_CONSC,/* XZAHC_ConvTypesMob[XZAEC_FMC_IncSsConces=19] */
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_FMC_FERM_ECH, 
	XDC_SYN_FMC_EBOULEMENT,		/* XZAHC_ConvTypesMob[XZAEC_FMC_Eboulement=22] */
	XDC_SYN_FMC_INCENDIE, 		/* XZAHC_ConvTypesMob[XZAEC_FMC_Incendie=23] */
	XDC_SYN_FMC_INONDATION,		/* XZAHC_ConvTypesMob[XZAEC_FMC_Inondation=24] */
	XDC_SYN_FMC_OBSTACLE, 		/* XZAHC_ConvTypesMob[XZAEC_FMC_Obstacle=25] */
	XDC_SYN_FMC_CHAUSSEE_DETERIOREE,/* XZAHC_ConvTypesMob[XZAEC_FMC_ChausseDeter=26] */
	XDC_SYN_FMC_FLAQUE_HUILE, 	/* XZAHC_ConvTypesMob[XZAEC_FMC_FlaqueHuile=27] */
	XDC_SYN_FMC_ANIMAL_ERRANT, 	/* XZAHC_ConvTypesMob[XZAEC_FMC_AnimalErrant=28] */
	XDC_SYN_FMC_FRONTIERE_FERMEE, 	/* XZAHC_ConvTypesMob[XZAEC_FMC_FrontiereFermee=29] */
	XDC_SYN_FMC_ALTERCATION_USAGERS,/* XZAHC_ConvTypesMob[XZAEC_FMC_AltercationUsager=30] */
	XDC_SYN_FMC_AGRESSION, 		/* XZAHC_ConvTypesMob[XZAEC_FMC_Agression=31] */
	XDC_SYN_FMC_MALAISE_USAGER, 	/* XZAHC_ConvTypesMob[XZAEC_FMC_MalaiseUsager=32] */
	XDC_SYN_FMC_HORS_RESEAU, 
	XDC_SYN_FMC_FERM_AIRE, 
	XDC_SYN_FMC_SALAGE, 
	XDC_SYN_FMC_HOLD_UP, 		/* XZAHC_ConvTypesMob[XZAEC_FMC_HoldUpVol=36] */
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_FMC_PIETON_CHAUSSEE, 	/* XZAHC_ConvTypesMob[XZAEC_FMC_PietonChaussee=38] */
	XDC_SYN_FMC_AUTRE, 		/* XZAHC_ConvTypesMob[XZAEC_FMC_Autre=39] */
	XDC_SYN_FMC_VEHICULE_MARCHE_ARR,	/* XZAHC_ConvTypesMob[XZAEC_FMC_VehMarcheArr=40] */
	XDC_SYN_FMC_TRAITEMENT_CHAUSSEES,	/* XZAHC_ConvTypesMob[XZAEC_FMC_TraitChaussees=41] */
	XDC_SYN_FMC_ECHANGEUR_DECONSEILLE,	/* XZAHC_ConvTypesMob[XZAEC_FMC_EchDeconseille=42] */
	XDC_SYN_FMC_CHAUSSEE_GLISSANTE,		/* XZAHC_ConvTypesMob[XZAEC_FMC_ChausseeGliss=43] */
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_FMC_ZONE_STOCKAGE,		/* XZAHC_ConvTypesMob[XZAEC_FMC_ZoneStockage=45] */ 
	XDC_SYN_FMC_REGULATION_VITESSE,		/* XZAHC_ConvTypesMob[XZAEC_FMC_Regulation=46]*/
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_FMC_ACCIDENT, 			/* XZAHC_ConvTypesMob[XZAHC_Accident=64] */
	XDC_SYN_FMC_ACCIDENT_VL, 		/* XZAHC_ConvTypesMob[65] */
	XDC_SYN_FMC_ACCIDENT_PL, 		/* XZAHC_ConvTypesMob[66] */
	XDC_SYN_FMC_ACCIDENT_VLPL, 		/* XZAHC_ConvTypesMob[67] */
	XDC_SYN_FMC_ACCIDENT_CAR, 		/* XZAHC_ConvTypesMob[68] */
	XDC_SYN_FMC_ACCIDENT_VLCAR, 		/* XZAHC_ConvTypesMob[69] */
	XDC_SYN_FMC_ACCIDENT_PLCAR, 		/* XZAHC_ConvTypesMob[70] */
	XDC_SYN_FMC_ACCIDENT_VLPLCAR, 		/* XZAHC_ConvTypesMob[71] */
	XDC_SYN_FMC_ACCIDENT_REM, 		/* XZAHC_ConvTypesMob[72] */
	XDC_SYN_FMC_ACCIDENT_VLREM, 		/* XZAHC_ConvTypesMob[73] */
	XDC_SYN_FMC_ACCIDENT_PLREM, 		/* XZAHC_ConvTypesMob[74] */
	XDC_SYN_FMC_ACCIDENT_VLPLREM, 		/* XZAHC_ConvTypesMob[75] */
	XDC_SYN_FMC_ACCIDENT_CARREM, 		/* XZAHC_ConvTypesMob[76] */
	XDC_SYN_FMC_ACCIDENT_VLCARREM, 		/* XZAHC_ConvTypesMob[77] */
	XDC_SYN_FMC_ACCIDENT_PLCARREM, 		/* XZAHC_ConvTypesMob[78] */
	XDC_SYN_FMC_ACCIDENT_VLPLCARREM, 	/* XZAHC_ConvTypesMob[79] */
	XDC_SYN_FMC_ACCIDENT_MOTO, 		/* XZAHC_ConvTypesMob[80] */
	XDC_SYN_FMC_ACCIDENT_VLMOTO, 		/* XZAHC_ConvTypesMob[81] */
	XDC_SYN_FMC_ACCIDENT_PLMOTO, 		/* XZAHC_ConvTypesMob[82] */
	XDC_SYN_FMC_ACCIDENT_VLPLMOTO, 		/* XZAHC_ConvTypesMob[83] */
	XDC_SYN_FMC_ACCIDENT_CARMOTO, 		/* XZAHC_ConvTypesMob[84] */
	XDC_SYN_FMC_ACCIDENT_VLCARMOTO, 	/* XZAHC_ConvTypesMob[85] */
	XDC_SYN_FMC_ACCIDENT_PLCARMOTO, 	/* XZAHC_ConvTypesMob[86] */
	XDC_SYN_FMC_ACCIDENT_VLPLCARMOTO, 	/* XZAHC_ConvTypesMob[87] */
	XDC_SYN_FMC_ACCIDENT_REMMOTO, 		/* XZAHC_ConvTypesMob[88] */
	XDC_SYN_FMC_ACCIDENT_VLREMMOTO, 	/* XZAHC_ConvTypesMob[89] */
	XDC_SYN_FMC_ACCIDENT_PLREMMOTO, 	/* XZAHC_ConvTypesMob[90] */
	XDC_SYN_FMC_ACCIDENT_VLPLREMMOTO, 	/* XZAHC_ConvTypesMob[91] */
	XDC_SYN_FMC_ACCIDENT_CARREMMOTO, 	/* XZAHC_ConvTypesMob[92] */
	XDC_SYN_FMC_ACCIDENT_VLCARREMMOTO, 	/* XZAHC_ConvTypesMob[93] */
	XDC_SYN_FMC_ACCIDENT_PLCARREMMOTO, 	/* XZAHC_ConvTypesMob[94] */
	XDC_SYN_FMC_ACCIDENT_VLPLCARREMMOTO, 	/* XZAHC_ConvTypesMob[95] */
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 

	XDC_SYN_OBJ_INCONNU, 	/* [100] */
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 

	XDC_SYN_OBJ_INCONNU, 		/* XZAHC_ConvTypesMob[XZAHC_Meteo=200] */
	XDC_SYN_FMC_METEO_CHUTE_NEIGE, 	/* XZAHC_ConvTypesMob[XZAHC_Meteo+XZAEC_MET_ChuteNeige=201] */
	XDC_SYN_FMC_METEO_NEIGE_CHAUSSEE,	/* XZAHC_ConvTypesMob[XZAHC_Meteo+XZAEC_MET_NeigeChaus=202] */
	XDC_SYN_FMC_METEO_PLUIE,	/* XZAHC_ConvTypesMob[XZAHC_Meteo+XZAEC_MET_Pluie=203] */ 
	XDC_SYN_FMC_METEO_VENT_FORT,	/* XZAHC_ConvTypesMob[XZAHC_Meteo+XZAEC_MET_VentFort=204] */ 
	XDC_SYN_FMC_METEO_BROUILLARD,	/* XZAHC_ConvTypesMob[XZAHC_Meteo+XZAEC_MET_Brouillard=205] */ 
	XDC_SYN_FMC_METEO_BROUILLARD_GIVRANT,	/* XZAHC_ConvTypesMob[XZAHC_Meteo+XZAEC_MET_BrouillardGiv=206] */ 
	XDC_SYN_FMC_METEO_GRELE,	/* XZAHC_ConvTypesMob[XZAHC_Meteo+XZAEC_MET_Grele=207] */ 
	XDC_SYN_FMC_METEO_VERGLAS,	/* XZAHC_ConvTypesMob[XZAHC_Meteo+XZAEC_MET_Verglas=208] */ 
	XDC_SYN_FMC_METEO_AUTRE,	/* XZAHC_ConvTypesMob[XZAHC_Meteo+XZAEC_MET_Autre=209] */ 
	XDC_SYN_FMC_METEO_GRELE_CHAUSSEE, /* XZAHC_ConvTypesMob[XZAHC_Meteo+XZAEC_MET_GreleChaus=210] */
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_OBJ_INCONNU, 
	XDC_SYN_INTERVENANT_AUTRE,		/* XZAHC_ConvTypesMob[XZAHC_Intervention=240] */ 
	XDC_SYN_TRAVAUX_MOBILES_QUEUE_REELS,	/* XZAHC_ConvTypesMob[XZAHC_Travaux_Mob_Queue_R=241] */
	XDC_SYN_TRAVAUX_MOBILES_TETE_REELS,	/* XZAHC_ConvTypesMob[XZAHC_Travaux_Mob_Tete_R=242] */
	XDC_SYN_TRAVAUX_MOBILES_QUEUE_PREVUS,	/* XZAHC_ConvTypesMob[XZAHC_Travaux_Mob_Queue_P=243] */
	XDC_SYN_TRAVAUX_MOBILES_TETE_PREVUS,	/* XZAHC_ConvTypesMob[XZAHC_Travaux_Mob_Tete_P=244] */
	XDC_SYN_GARE,				/* XZAHC_ConvTypesMob[XZAHC_Gare=245] */
	XDC_SYN_PMV_MOBILE,			/* XZAHC_ConvTypesMob[XZAHC_PMV_Mobile=246] */
	XDC_SYN_INTERVENANT_PAT_ESCOTA,		/* XZAHC_ConvTypesMob[XZAHC_Patrouille=247] */
	XDC_SYN_INTERVENANT_FOURGON_SIS,	/* XZAHC_ConvTypesMob[XZAHC_PMV_Fourgon=248] */
	XDC_SYN_INTERVENANT_DEPANNEUR,		/* XZAHC_ConvTypesMob[XZAHC_Depanneur=249] */
	XDC_SYN_INTERVENANT_POMPIER,		/* XZAHC_ConvTypesMob[XZAHC_Pompier=250] */
	XDC_SYN_INTERVENANT_GENDARMERIE,	/* XZAHC_ConvTypesMob[XZAHC_Gendarme=251] */
	XDC_SYN_TRAVAUX_FIXES_REELS,		/* XZAHC_ConvTypesMob[XZAHC_Travaux_Fix_R=252] */
	XDC_SYN_TRAVAUX_FIXES_PREVUS,		/* XZAHC_ConvTypesMob[XZAHC_Travaux_Fix_P=253] */
	XDC_SYN_TRAVAUX_MOBILES_REELS,		/* XZAHC_ConvTypesMob[XZAHC_Travaux_Mob_R=254] */
	XDC_SYN_TRAVAUX_MOBILES_PREVUS		/* XZAHC_ConvTypesMob[XZAHC_Travaux_Mob_P=255] */
	};


/* delaration de fonctions externes */

