# Création des tables de la base des données CFG pour le site CA

table.sh cfg ada_evt CA
table.sh cfg ada_pmv CA
table.sh cfg ada_sta CA
table.sh cfg alt_inh CA
table.sh cfg ann_ast_cal CA
table.sh cfg ann_ast_cat CA
table.sh cfg ann_ast_cmp CA
table.sh cfg ann_cit CA
table.sh cfg ann_cmp CA
table.sh cfg ann_fic CA
table.sh cfg ann_geo CA
table.sh cfg apl_mtf CA
table.sh cfg cal_vac CA
table.sh cfg cch_tro CA
table.sh cfg def_bou CA
table.sh cfg def_pdf CA
table.sh cfg dtp_pma CA
table.sh cfg dtp_pmv CA
table.sh cfg eqt_alm CA
table.sh cfg eqt_ana CA
table.sh cfg eqt_bad CA
table.sh cfg eqt_baf CA
table.sh cfg eqt_cam CA
table.sh cfg eqt_cam_pos CA
table.sh cfg eqt_cap CA
table.sh cfg eqt_cfe CA
table.sh cfg eqt_cpt CA
table.sh cfg eqt_dai CA
table.sh cfg eqt_ech CA
table.sh cfg eqt_eht CA
table.sh cfg eqt_fav CA
table.sh cfg eqt_fax CA
table.sh cfg eqt_gen CA
table.sh cfg eqt_gtc CA
table.sh cfg eqt_gtc_ecl CA
table.sh cfg eqt_gtc_enr CA
table.sh cfg eqt_gtc_exp CA
table.sh cfg eqt_gtc_inc CA
table.sh cfg eqt_gtc_ltn CA
table.sh cfg eqt_gtc_sig CA
table.sh cfg eqt_gtc_sys CA
table.sh cfg eqt_gtc_ven CA
table.sh cfg eqt_imu CA
table.sh cfg eqt_imu_msg CA
table.sh cfg eqt_imu_zon CA
table.sh cfg eqt_isi CA
table.sh cfg eqt_lcr CA
table.sh cfg eqt_lit CA
table.sh cfg eqt_loc CA
table.sh cfg eqt_ltn CA
table.sh cfg eqt_ltv CA
table.sh cfg eqt_ltv_can CA
table.sh cfg eqt_maa CA
table.sh cfg eqt_mac CA
table.sh cfg eqt_mag CA
table.sh cfg eqt_mnt CA
table.sh cfg eqt_mod CA
table.sh cfg eqt_modbad CA
table.sh cfg eqt_modbaf CA
table.sh cfg eqt_nav CA
table.sh cfg eqt_nic CA
table.sh cfg eqt_pal CA
table.sh cfg eqt_pan CA
table.sh cfg eqt_pau CA
table.sh cfg eqt_pct CA
table.sh cfg eqt_pmv CA
table.sh cfg eqt_pmva CA
table.sh cfg eqt_pnt_mes CA
table.sh cfg eqt_prv CA
table.sh cfg eqt_rad CA
table.sh cfg eqt_rad_vtl CA
table.sh cfg eqt_rau CA
table.sh cfg eqt_saga CA
table.sh cfg eqt_scn_cnn CA
table.sh cfg eqt_scn_nav CA
table.sh cfg eqt_seq_ech CA
table.sh cfg eqt_seq_gtc_ecl CA
table.sh cfg eqt_seq_gtc_enr CA
table.sh cfg eqt_seq_gtc_exp CA
table.sh cfg eqt_seq_gtc_inc CA
table.sh cfg eqt_seq_gtc_sig CA
table.sh cfg eqt_seq_gtc_ven CA
table.sh cfg eqt_seq_tub CA
table.sh cfg eqt_sqa_ech CA
table.sh cfg eqt_sqa_gtc_ecl CA
table.sh cfg eqt_sqa_gtc_enr CA
table.sh cfg eqt_sqa_gtc_exp CA
table.sh cfg eqt_sqa_gtc_inc CA
table.sh cfg eqt_sqa_gtc_sig CA
table.sh cfg eqt_sqa_gtc_ven CA
table.sh cfg eqt_sqa_tub CA
table.sh cfg eqt_sqr_gtc_sig CA
table.sh cfg eqt_sys CA
table.sh cfg eqt_syv CA
table.sh cfg eqt_tdp CA
table.sh cfg eqt_tor CA
table.sh cfg eqt_tub CA
table.sh cfg eqt_zdp CA
table.sh cfg eta_eqt CA
table.sh cfg frn_lis CA
table.sh cfg lib_pre CA
table.sh cfg lib_typ CA
table.sh cfg loc_gps CA
table.sh cfg loc_rds CA
table.sh cfg lst_fmc_blc CA
table.sh cfg lst_fmc_col CA
table.sh cfg lst_fmc_mac CA
table.sh cfg mga_par_ref CA
table.sh cfg nom_rds CA
table.sh cfg num_rds CA
table.sh cfg opr_fct_mac CA
table.sh cfg opr_fct_nom CA
table.sh cfg opr_ide CA
table.sh cfg opr_log_mdp CA
table.sh cfg opr_nom CA
table.sh cfg opr_prf CA
table.sh cfg opr_prf_fct CA
table.sh cfg pln_scr CA
table.sh cfg pr_rds CA
table.sh cfg reg_ass CA
table.sh cfg reg_com CA
table.sh cfg reg_con CA
table.sh cfg reg_par CA
table.sh cfg reg_sce CA
table.sh cfg reg_sce_cmd CA
table.sh cfg reg_typ CA
table.sh cfg res_air CA
table.sh cfg res_aut CA
table.sh cfg res_aut_inv CA
table.sh cfg res_bas CA
table.sh cfg res_can CA
table.sh cfg res_cha CA
table.sh cfg res_dis CA
table.sh cfg res_dit CA
table.sh cfg res_dtp CA
table.sh cfg res_ech CA
table.sh cfg res_inf CA
table.sh cfg res_itp CA
table.sh cfg res_jon CA
table.sh cfg res_neu CA
table.sh cfg res_nic_is CA
table.sh cfg res_num_ech CA
table.sh cfg res_pea CA
table.sh cfg res_pnt CA
table.sh cfg res_pol CA
table.sh cfg res_por CA
table.sh cfg res_pra CA
table.sh cfg res_ptl CA
table.sh cfg res_ref_va CA
table.sh cfg res_sec CA
table.sh cfg res_sec_por CA
table.sh cfg res_seg CA
table.sh cfg res_sup CA
table.sh cfg res_trc CA
table.sh cfg res_trn CA
table.sh cfg res_via CA
table.sh cfg res_vil CA
table.sh cfg sad_aut CA
table.sh cfg sad_cfg CA
table.sh cfg syn_lib_flt CA
table.sh cfg syn_pse CA
table.sh cfg syn_ptc_loc CA
table.sh cfg tdp_arr_fcd CA
table.sh cfg typ_alm CA
table.sh cfg typ_alt CA
table.sh cfg typ_ast CA
table.sh cfg typ_crb CA
table.sh cfg typ_fmc CA
table.sh cfg typ_fmc_grp CA
table.sh cfg typ_nav CA
table.sh cfg typ_pct CA
table.sh cfg typ_pmv CA
table.sh cfg web_air CA
table.sh cfg web_ech CA
table.sh cfg web_fmc CA
table.sh cfg web_tro CA
table.sh cfg zon_bad CA
table.sh cfg zon_baf CA
table.sh cfg zon_baf_saga CA
table.sh cfg zon_pma CA
table.sh cfg zon_pma_saga CA
table.sh cfg zon_pmv CA
table.sh cfg zon_pmv_saga CA
table.sh cfg zon_rau CA
table.sh cfg zon_reg CA
table.sh cfg zon_tun CA
table.sh cfg zon_urb CA