# Création des tables de la base des données EXP pour le site CA

table.sh exp act_ada CA
table.sh exp act_apl CA
table.sh exp act_bad CA
table.sh exp act_baf CA
table.sh exp act_cch CA
table.sh exp act_cfe CA
table.sh exp act_dep CA
table.sh exp act_ech CA
table.sh exp act_exp_ada CA
table.sh exp act_fax CA
table.sh exp act_frg CA
table.sh exp act_gar CA
table.sh exp act_gen CA
table.sh exp act_gtc_ecl CA
table.sh exp act_gtc_enr CA
table.sh exp act_gtc_exp CA
table.sh exp act_gtc_inc CA
table.sh exp act_gtc_sig CA
table.sh exp act_gtc_ven CA
table.sh exp act_imu CA
table.sh exp act_int CA
table.sh exp act_nav CA
table.sh exp act_pal CA
table.sh exp act_pau CA
table.sh exp act_pma CA
table.sh exp act_pmv CA
table.sh exp act_pmv_ada CA
table.sh exp act_prv CA
table.sh exp act_rmq CA
table.sh exp act_saga CA
table.sh exp act_sis CA
table.sh exp act_tfm CA
table.sh exp act_tfm_exp CA
table.sh exp act_tub CA
table.sh exp act_txt_tfm CA
table.sh exp ada_act CA
table.sh exp ada_fmc CA
table.sh exp ada_sit CA
table.sh exp ada_syn CA
table.sh exp ada_txt_syn CA
table.sh exp alm_eqt CA
table.sh exp alm_ihm CA
table.sh exp alm_nbr CA
table.sh exp alt_cau_his CA
table.sh exp alt_exp CA
table.sh exp alt_loc CA
table.sh exp apl_fax CA
table.sh exp bas_rau CA
table.sh exp bas_rau_tra CA
table.sh exp eqt_acv CA
table.sh exp eqt_dsp CA
table.sh exp eqt_fil CA
table.sh exp eqt_fil_trv CA
table.sh exp eqt_tdp_inh CA
table.sh exp eta_eqt CA
table.sh exp fmc_acc CA
table.sh exp fmc_act CA
table.sh exp fmc_ada CA
table.sh exp fmc_bas CA
table.sh exp fmc_bou CA
table.sh exp fmc_cnc CA
table.sh exp fmc_com CA
table.sh exp fmc_commu CA
table.sh exp fmc_dat CA
table.sh exp fmc_del CA
table.sh exp fmc_ech CA
table.sh exp fmc_gen CA
table.sh exp fmc_his CA
table.sh exp fmc_his_der CA
table.sh exp fmc_inc CA
table.sh exp fmc_lis CA
table.sh exp fmc_met CA
table.sh exp fmc_met_cch CA
table.sh exp fmc_mnf CA
table.sh exp fmc_nat CA
table.sh exp fmc_opr CA
table.sh exp fmc_pur CA
table.sh exp fmc_ref_ext CA
table.sh exp fmc_reg CA
table.sh exp fmc_rev CA
table.sh exp fmc_sat CA
table.sh exp fmc_syn CA
table.sh exp fmc_tfm CA
table.sh exp fmc_tra CA
table.sh exp fmc_trf CA
table.sh exp fmc_trh CA
table.sh exp fmc_trs CA
table.sh exp fmc_trt CA
table.sh exp fmc_veh CA
table.sh exp fmc_vln CA
table.sh exp frn_tdp CA
table.sh exp gab_tra CA
table.sh exp lst_cpt CA
table.sh exp mes_ada CA
table.sh exp mes_kcs CA
table.sh exp mes_nec CA
table.sh exp mes_niv CA
table.sh exp mes_niv_der CA
table.sh exp mes_poi CA
table.sh exp mes_qpc CA
table.sh exp mes_tra CA
table.sh exp mga_cfg_po CA
table.sh exp mga_msg_po CA
table.sh exp mga_msg_prg CA
table.sh exp opr_ihm_prf CA
table.sh exp pit_log CA
table.sh exp pmv_ada CA
table.sh exp pmv_ntr CA
table.sh exp prg_pma CA
table.sh exp prg_pma_saga CA
table.sh exp prg_pmv CA
table.sh exp prg_pmv_saga CA
table.sh exp ref_alt_pit_acqt CA
table.sh exp ref_pit_message CA
table.sh exp reg_tra CA
table.sh exp rs_dbversion CA
table.sh exp rs_lastcommit CA
table.sh exp rs_mat_status CA
table.sh exp rs_threads CA
table.sh exp rs_ticket_history CA
table.sh exp sad_apl CA
table.sh exp sad_bad CA
table.sh exp sad_baf CA
table.sh exp sad_cfe CA
table.sh exp sad_dst_fax CA
table.sh exp sad_ech CA
table.sh exp sad_exp CA
table.sh exp sad_fax CA
table.sh exp sad_imu CA
table.sh exp sad_msg_tfm CA
table.sh exp sad_nav CA
table.sh exp sad_pal CA
table.sh exp sad_pln CA
table.sh exp sad_pma CA
table.sh exp sad_pmv CA
table.sh exp sad_prv CA
table.sh exp sad_pic CA
table.sh exp sad_saga CA
table.sh exp sad_sono CA
table.sh exp sad_tfm CA
table.sh exp sad_tub CA
table.sh exp sad_txt_fax CA
table.sh exp sad_txt_tfm CA
table.sh exp syn_bas_seg CA
table.sh exp syn_bou_por CA
table.sh exp syn_bou_seg CA
table.sh exp syn_inv_seg CA
table.sh exp syn_neu_seg CA
table.sh exp syn_obj_por CA
table.sh exp syn_obj_seg CA
table.sh exp syn_rab_seg CA
table.sh exp tdp_fcd CA
table.sh exp tfm_ada CA
table.sh exp tfm_dtx CA
table.sh exp tfm_tdp CA
table.sh exp voi_dai CA
table.sh exp voi_rad CA
table.sh exp web_cri CA
table.sh exp web_evt CA
table.sh exp web_txt CA
table.sh exp zdp_6mn CA