# Création des tables de la base des données CFT pour le site CA

table.sh cft ada_evt CA
table.sh cft ada_pmv CA
table.sh cft ada_sta CA
table.sh cft alt_inh CA
table.sh cft ann_ast_cal CA
table.sh cft ann_ast_cat CA
table.sh cft ann_ast_cmp CA
table.sh cft ann_cit CA
table.sh cft ann_cmp CA
table.sh cft ann_fic CA
table.sh cft ann_geo CA
table.sh cft apl_mtf CA
table.sh cft cal_vac CA
table.sh cft cch_tro CA
table.sh cft def_bou CA
table.sh cft def_pdf CA
table.sh cft dtp_pma CA
table.sh cft dtp_pmv CA
table.sh cft eqt_alm CA
table.sh cft eqt_ana CA
table.sh cft eqt_bad CA
table.sh cft eqt_baf CA
table.sh cft eqt_cam CA
table.sh cft eqt_cam_pos CA
table.sh cft eqt_cap CA
table.sh cft eqt_cfe CA
table.sh cft eqt_cpt CA
table.sh cft eqt_dai CA
table.sh cft eqt_ech CA
table.sh cft eqt_eht CA
table.sh cft eqt_fav CA
table.sh cft eqt_fax CA
table.sh cft eqt_gen CA
table.sh cft eqt_gtc CA
table.sh cft eqt_gtc_ecl CA
table.sh cft eqt_gtc_enr CA
table.sh cft eqt_gtc_exp CA
table.sh cft eqt_gtc_inc CA
table.sh cft eqt_gtc_ltn CA
table.sh cft eqt_gtc_sig CA
table.sh cft eqt_gtc_sys CA
table.sh cft eqt_gtc_ven CA
table.sh cft eqt_imu CA
table.sh cft eqt_imu_msg CA
table.sh cft eqt_imu_zon CA
table.sh cft eqt_isi CA
table.sh cft eqt_lcr CA
table.sh cft eqt_lit CA
table.sh cft eqt_loc CA
table.sh cft eqt_ltn CA
table.sh cft eqt_ltv CA
table.sh cft eqt_ltv_can CA
table.sh cft eqt_maa CA
table.sh cft eqt_mac CA
table.sh cft eqt_mag CA
table.sh cft eqt_mnt CA
table.sh cft eqt_mod CA
table.sh cft eqt_modbad CA
table.sh cft eqt_modbaf CA
table.sh cft eqt_nav CA
table.sh cft eqt_nic CA
table.sh cft eqt_pal CA
table.sh cft eqt_pan CA
table.sh cft eqt_pau CA
table.sh cft eqt_pct CA
table.sh cft eqt_pmv CA
table.sh cft eqt_pmva CA
table.sh cft eqt_pnt_mes CA
table.sh cft eqt_prv CA
table.sh cft eqt_rad CA
table.sh cft eqt_rad_vtl CA
table.sh cft eqt_rau CA
table.sh cft eqt_saga CA
table.sh cft eqt_scn_cnn CA
table.sh cft eqt_scn_nav CA
table.sh cft eqt_seq_ech CA
table.sh cft eqt_seq_gtc_ecl CA
table.sh cft eqt_seq_gtc_enr CA
table.sh cft eqt_seq_gtc_exp CA
table.sh cft eqt_seq_gtc_inc CA
table.sh cft eqt_seq_gtc_sig CA
table.sh cft eqt_seq_gtc_ven CA
table.sh cft eqt_seq_tub CA
table.sh cft eqt_sqa_ech CA
table.sh cft eqt_sqa_gtc_ecl CA
table.sh cft eqt_sqa_gtc_enr CA
table.sh cft eqt_sqa_gtc_exp CA
table.sh cft eqt_sqa_gtc_inc CA
table.sh cft eqt_sqa_gtc_sig CA
table.sh cft eqt_sqa_gtc_ven CA
table.sh cft eqt_sqa_tub CA
table.sh cft eqt_sqr_gtc_sig CA
table.sh cft eqt_sys CA
table.sh cft eqt_syv CA
table.sh cft eqt_tdp CA
table.sh cft eqt_tor CA
table.sh cft eqt_tub CA
table.sh cft eqt_zdp CA
table.sh cft eta_eqt CA
table.sh cft frn_lis CA
table.sh cft lib_pre CA
table.sh cft lib_typ CA
table.sh cft loc_gps CA
table.sh cft loc_rds CA
table.sh cft lst_fmc_blc CA
table.sh cft lst_fmc_col CA
table.sh cft lst_fmc_mac CA
table.sh cft mga_par_ref CA
table.sh cft nom_rds CA
table.sh cft num_rds CA
table.sh cft opr_fct_mac CA
table.sh cft opr_fct_nom CA
table.sh cft opr_ide CA
table.sh cft opr_log_mdp CA
table.sh cft opr_nom CA
table.sh cft opr_prf CA
table.sh cft opr_prf_fct CA
table.sh cft pln_scr CA
table.sh cft pr_rds CA
table.sh cft reg_ass CA
table.sh cft reg_com CA
table.sh cft reg_con CA
table.sh cft reg_par CA
table.sh cft reg_sce CA
table.sh cft reg_sce_cmd CA
table.sh cft reg_typ CA
table.sh cft res_air CA
table.sh cft res_aut CA
table.sh cft res_aut_inv CA
table.sh cft res_bas CA
table.sh cft res_can CA
table.sh cft res_cha CA
table.sh cft res_dis CA
table.sh cft res_dit CA
table.sh cft res_dtp CA
table.sh cft res_ech CA
table.sh cft res_inf CA
table.sh cft res_itp CA
table.sh cft res_jon CA
table.sh cft res_neu CA
table.sh cft res_nic_is CA
table.sh cft res_num_ech CA
table.sh cft res_pea CA
table.sh cft res_pnt CA
table.sh cft res_pol CA
table.sh cft res_por CA
table.sh cft res_pra CA
table.sh cft res_ptl CA
table.sh cft res_ref_va CA
table.sh cft res_sec CA
table.sh cft res_sec_por CA
table.sh cft res_seg CA
table.sh cft res_sup CA
table.sh cft res_trc CA
table.sh cft res_trn CA
table.sh cft res_via CA
table.sh cft res_vil CA
table.sh cft sad_aut CA
table.sh cft sad_cfg CA
table.sh cft syn_lib_flt CA
table.sh cft syn_pse CA
table.sh cft syn_ptc_loc CA
table.sh cft tdp_arr_fcd CA
table.sh cft typ_alm CA
table.sh cft typ_alt CA
table.sh cft typ_ast CA
table.sh cft typ_crb CA
table.sh cft typ_fmc CA
table.sh cft typ_fmc_grp CA
table.sh cft typ_nav CA
table.sh cft typ_pct CA
table.sh cft typ_pmv CA
table.sh cft web_air CA
table.sh cft web_ech CA
table.sh cft web_fmc CA
table.sh cft web_tro CA
table.sh cft zon_bad CA
table.sh cft zon_baf CA
table.sh cft zon_baf_saga CA
table.sh cft zon_pma CA
table.sh cft zon_pma_saga CA
table.sh cft zon_pmv CA
table.sh cft zon_pmv_saga CA
table.sh cft zon_rau CA
table.sh cft zon_reg CA
table.sh cft zon_tun CA
table.sh cft zon_urb CA