# Création des tables de la base des données HIS pour le site HIS/CNA

table.sh his act_ada HIS
table.sh his act_apl HIS
table.sh his act_bad HIS
table.sh his act_baf HIS
table.sh his act_cch HIS
table.sh his act_cfe HIS
table.sh his act_dep HIS
table.sh his act_ech HIS
table.sh his act_exp_ada HIS
table.sh his act_fax HIS
table.sh his act_frg HIS
table.sh his act_gar HIS
table.sh his act_gen HIS
table.sh his act_gtc_ecl HIS
table.sh his act_gtc_enr HIS
table.sh his act_gtc_exp HIS
table.sh his act_gtc_inc HIS
table.sh his act_gtc_sig HIS
table.sh his act_gtc_ven HIS
table.sh his act_imu HIS
table.sh his act_int HIS
table.sh his act_nav HIS
table.sh his act_pal HIS
table.sh his act_pau HIS
table.sh his act_pma HIS
table.sh his act_pmv HIS
table.sh his act_pmv_ada HIS
table.sh his act_prv HIS
table.sh his act_rmq HIS
table.sh his act_saga HIS
table.sh his act_sis HIS
table.sh his act_tfm HIS
table.sh his act_tfm_exp HIS
table.sh his act_tub HIS
table.sh his act_txt_tfm HIS
table.sh his ada_fmc HIS
table.sh his alm_eqt HIS
table.sh his alm_ihm HIS
table.sh his alm_nbr HIS
table.sh his alt_cau_his HIS
table.sh his alt_exp HIS
table.sh his alt_loc HIS
table.sh his apl_fax HIS
table.sh his apl_hor HIS
table.sh his bas_rau HIS
table.sh his bas_rau_tra HIS
table.sh his eqt_acv HIS
table.sh his eqt_dsp HIS
table.sh his eqt_fil HIS
table.sh his eqt_fil_trv HIS
table.sh his eqt_imu HIS
table.sh his eqt_tdp_inh HIS
table.sh his fmc_acc HIS
table.sh his fmc_ada HIS
table.sh his fmc_bas HIS
table.sh his fmc_bou HIS
table.sh his fmc_cnc HIS
table.sh his fmc_com HIS
table.sh his fmc_commu HIS
table.sh his fmc_dat HIS
table.sh his fmc_del HIS
table.sh his fmc_ech HIS
table.sh his fmc_gen HIS
table.sh his fmc_his HIS
table.sh his fmc_inc HIS
table.sh his fmc_lis HIS
table.sh his fmc_met HIS
table.sh his fmc_met_cch HIS
table.sh his fmc_mnf HIS
table.sh his fmc_nat HIS
table.sh his fmc_opr HIS
table.sh his fmc_pur HIS
table.sh his fmc_ref_ext HIS
table.sh his fmc_reg HIS
table.sh his fmc_rev HIS
table.sh his fmc_syn HIS
table.sh his fmc_tfm HIS
table.sh his fmc_tra HIS
table.sh his fmc_trf HIS
table.sh his fmc_trh HIS
table.sh his fmc_trt HIS
table.sh his fmc_veh HIS
table.sh his fmc_vln HIS
table.sh his gab_tra HIS
table.sh his lst_cpt HIS
table.sh his mes_ada HIS
table.sh his mes_kcs HIS
table.sh his mes_met HIS
table.sh his mes_nec HIS
table.sh his mes_niv HIS
table.sh his mes_poi HIS
table.sh his mes_qpc HIS
table.sh his mes_tra HIS
table.sh his mga_cfg_po HIS
table.sh his mga_msg_po HIS
table.sh his mga_msg_prg HIS
table.sh his msg_tra HIS
table.sh his opr_ihm_prf HIS
table.sh his pit_log HIS
table.sh his pmv_ada HIS
table.sh his pmv_ntr HIS
table.sh his prg_pma HIS
table.sh his prg_pmv HIS
table.sh his prg_pmv_saga HIS
table.sh his ref_alt_pit_acqt HIS
table.sh his ref_pit_message HIS
table.sh his reg_tra HIS
table.sh his rs_dbversion HIS
table.sh his rs_lastcommit HIS
table.sh his rs_mat_status HIS
table.sh his rs_threads HIS
table.sh his rs_ticket_history HIS
table.sh his sad_baf HIS
table.sh his sad_imu HIS
table.sh his sad_sono HIS
table.sh his syn_bou_por HIS
table.sh his syn_bou_seg HIS
table.sh his syn_inv_seg HIS
table.sh his syn_neu_seg HIS
table.sh his syn_obj_por HIS
table.sh his syn_rab_seg HIS
table.sh his sys_inq HIS
table.sh his tdp_fcd HIS
table.sh his tfm_ada HIS
table.sh his tfm_tdp HIS
table.sh his voi_dai HIS
table.sh his voi_rad HIS
table.sh his web_cri HIS
table.sh his zdp_6mn HIS
table.sh his zdp_heu HIS