Elaboration des messages TFM;;1;;;
Evènements à ne pas inclure;tfm_evenements;2;;;
Mise en évidence des textes relatifs aux travaux;tfm_travaux;2;;;
Définition des objectifs d'information TFM;tfm_objectifs;2;;;
Formulation des éléments de message;;2;;;
Nature d'un évènement (groupe nominal);tfm_naturegn;3;;;
Nature d'un évènement (groupe verbal);tfm_naturegv;3;;;
Fin d'un évènement;tfm_fin;3;;;
Cause d'un évènement;tfm_cause;3;;;
Autoroutes et sens;tfm_autoroutes;3;;;
Chaussée glissante;tfm_chaussee;3;;;
Conseil;tfm_conseil;3;;;
Durée;tfm_duree;3;;;
Gravité;tfm_gravite;3;;;
Guidage;tfm_guidage;3;;;
Heure de début;tfm_debut;3;;;
Localisation;tfm_local;3;;;
Longueur de bouchon;tfm_bouchon;3;;;
Neutralisation de voies;tfm_neutralisees;3;;;
Période;tfm_periode;3;;;
Retour a la normale;tfm_retour;3;;;
Secours;tfm_secours;3;;;
Véhicules impliqués;tfm_vehicules;3;;;
Victimes;tfm_victimes;3;;;
Visibilité;tfm_visibilite;3;;;
Voies bloquées;tfm_bloquees;3;;;
Temps de parcours perturbé;tfm_tdp_perturbe;2;;;
Retour à la normale du temps de parcours;tfm_tdp_normal;2;;;
Entete Message Partenaire;tfm_entete;2;;;
Choix des interlocuteurs;;1;;;
Dans les PC;;2;;;
Interlocuteurs;interl_PC;3;;;
Cas d'appel;interl_casPC;3;;;
Appels différés;interl_differePC;3;;;
Au CI;;2;;;
Interlocuteurs;interl_CI;3;;;
Cas d'appel;interl_casCI;3;;;
Appels différés;interl_differeCI;3;;;
Elaboration des fax;;1;;;
Mise en évidence des textes relatifs aux travaux;fax_travaux;2;;;
Structure d'un fax;fax_structure;2;;;
Intitulés des rubriques;fax_intitules;2;;;
Formulation des rubriques;;2;;;
Rubrique Affichage en gare;fax_gare;3;;;
Rubrique Autoroute;fax_autoroute;3;;;
Rubrique Conséquences;fax_consequences;3;;;
Rubrique Difficultés de circulation;fax_circulation;3;;;
Rubrique Gravité;fax_gravite;3;;;
Rubrique Heure de début;fax_debut;3;;;
Rubrique Heure de fin;fax_fin;3;;;
Rubrique Information sur PMV;fax_pmv;3;;;
Rubrique Matières dangereuses;fax_matieres;3;;;
Rubrique Nombre de véhicules;fax_vehicules;3;;;
Rubrique Objet;fax_objet;3;;;
Rubrique PR;fax_pr;3;;;
Rubrique Remarques;fax_remarques;3;;;
Rubrique Restrictions de circulation;fax_neutralisees;3;;;
Rubrique Section;fax_section;3;;;
Rubrique Sens;fax_sens;3;;;
Rubrique Voies bloquées;fax_bloquees;3;;;
Fax spécial police;fax_police;2;;;
Pilotage PMV;;1;;;
Définition des objectifs d'information PMV;pmv_objectifs;2;;;
Définition des perturbations PMV;pmv_perturbations;2;;;
Définition des messages PMV particuliers;pmv_predefini;2;;;
Formulation des éléments de message PMV;;2;;;
Formulation de l'élément cause;pmv_formulCause;3;;;
Formulation de l'élément conseil;pmv_formulConseil;3;;;
Formulation de l'élément direction;pmv_formulDirection;3;;;
Formulation de l'élément durée de l'évènement;pmv_formulDuree;3;;;
Formulation de l'élément localisation;pmv_formulLocalisation;3;;;
Formulation de l'élément longueur de bouchon;pmv_formulBouchon;3;;;
Formulation de l'élément nature - cas général;pmv_formulNature;3;;;
Formulation de l'élément nature - cas déviation et délestage;pmv_formulNatureDel;3;;;
Formulation de l'élément probabilité;pmv_formulProba;3;;;
Stratégie de localisation;strategie_sortie;2;;;
Définition du texte d'alternat;pmv_alternat;2;;;
Choix du pictogramme;pmv_picto;2;;;
Choix du texte sur bandeau;pmv_bandeau;2;;;
Message Temps de Parcours non lie à un événement;pmv_tdp;2;;;
Pilotage signalisation tunnel;;1;;;
Définition  des PR de fin de zone de compétence;tunnel_pr;2;;;
Pilotage BRA;;1;;;
Définition  des PR de fin de zone de compétence;nav_pr;2;;;
Relations entre évènements et modes de fonctionnement;nav_relations;2;;;
Export;;1;;;
Export Intergestionnaires;export;2;;;
Priorité actions;;1;;;
Ordre des actions PC;actions_pc;2;;;
Ordre des actions CI;actions_ci;2;;;
Générer BDC;;1;;;
Générer les règles TFM;gen_tfm;2;;;
Générer les règles de choix des interlocuteurs;gen_interl;2;;;
Générer les règles fax;gen_fax;2;;;
Générer les règles PMV;gen_pmv;2;;;
Générer les règles BRA;gen_nav;2;;;
Générer les règles de priorité;gen_priorite;2;;;
Générer les règles d'export intergestionnaires;gen_export;2;;;
Générer toute la base de connaissances;gen_tout;2;;;
Imprimer;;1;;;
Imprimer les règles TFM;imprim_tfm;2;;;
Imprimer les règles de choix des interlocuteurs;imprim_interl;2;;;
Imprimer les règles fax;imprim_fax;2;;;
Imprimer les règles PMV;imprim_pmv;2;;;
Imprimer les règles BRA;imprim_nav;2;;;
Imprimer les règles de priorité;imprim_priorite;2;;;
Imprimer les règles d'export intergestionnaires;imprim_export;2;;;
Imprimer toute la base de connaissances;imprim_tout;2;;;
Pilotage;;1;;;
Afficher l'aide en ligne;aide;2;;;
Quitter;quitter;2;;;
