/*X Fichier : $Id: scon_dir.h,v 1.3 1994/12/14 09:03:55 milleville Exp $      Release : $Revision: 1.3 $        Date : $Date: 1994/12/14 09:03:55 $
------------------------------------------------------
* STERIA *  PROJET MIGRAZUR
------------------------------------------------------
* SOUS-SYSTEME TSCONF
------------------------------------------------------
* MODULE SCON_DIR * FICHIER SCON_DIR.h
------------------------------------------------------
* DESCRIPTION DU MODULE :
*
* Module associee au fichier SCON_DIR
*
------------------------------------------------------
* HISTORIQUE :
*
* T.Milleville	30 Aug 1994	: Creation
------------------------------------------------------*/

#ifndef SCON_DIR
#define SCON_DIR

/* fichiers inclus */

/* definitions de constantes exportees */

/* definitions de types exportes */

/* definition de macro exportees */

/* declarations de donnees globales */

/* delaration de fonctions externes */

/*
** Generated by X-Designer 
*/

extern void create_BDSSY (Widget, MrmHierarchy, MrmCode *);

extern void create_BDCAL (Widget, MrmHierarchy, MrmCode *);

extern void create_BDSIT (Widget, MrmHierarchy, MrmCode *);

extern void create_BDCTM (Widget, MrmHierarchy, MrmCode *);

extern void create_BDCMA (Widget, MrmHierarchy, MrmCode *);

extern void create_BDCOMA (Widget, MrmHierarchy, MrmCode *);

extern void create_BDTAC (Widget, MrmHierarchy, MrmCode *);

extern void create_BDMAC (Widget, MrmHierarchy, MrmCode *);

extern void create_CONFM (Display *, char *, int, char **, MrmHierarchy, MrmCode *);

#endif
