/*
** Generated by X-Designer 
*/
/*
**LIBS: -lXm -lXt -lX11
*/

#include <X11/Xatom.h>
#include <X11/Intrinsic.h>
#include <X11/Shell.h>

#include <Xm/Xm.h>
#include <Xm/DialogS.h>
#include <Xm/Form.h>
#include <Xm/Label.h>
#include <Xm/PushB.h>
#include <stdio.h>

static int tab_cr[4];

void BTactivateCb (Widget w, XtPointer client_data, XtPointer call_data)
{
    exit(tab_cr[(int)client_data]);
}

void XDmanage_link (Widget w, XtPointer client_data, XtPointer call_data)
{
    XtManageChild ( *(Widget *)client_data );
}

void XDunmanage_link (Widget w, XtPointer client_data, XtPointer call_data)
{
    XtUnmanageChild ( *(Widget *)client_data );
}

void XDpopup_link (Widget w, XtPointer client_data, XtPointer call_data)
{
    XtPopup ( *(Widget *)client_data, XtGrabNone );
}

void XDpopdown_link (Widget w, XtPointer client_data, XtPointer call_data)
{
    XtPopdown ( *(Widget *)client_data );
}

void XDmap_link (Widget w, XtPointer client_data, XtPointer call_data)
{
    XtMapWidget (*(Widget *)client_data);
}

void XDunmap_link (Widget w, XtPointer client_data, XtPointer call_data)
{
    XtUnmapWidget (*(Widget *)client_data);
}

void XDenable_link (Widget w, XtPointer client_data, XtPointer call_data)
{
    XtSetSensitive (*(Widget *)client_data, TRUE);
}

void XDdisable_link (Widget w, XtPointer client_data, XtPointer call_data)
{
    XtSetSensitive (*(Widget *)client_data, FALSE);
}


Widget toplevel = (Widget) NULL;
Widget LLmsg = (Widget) NULL;
Widget BT1 = (Widget) NULL;
Widget BT2 = (Widget) NULL;
Widget BT3 = (Widget) NULL;



void create_toplevel (Display *display, char *app_name, int app_argc, char **app_argv)
{
	Widget children[4];      /* Children to manage */
	Arg al[64];                    /* Arg List */
	register int ac = 0;           /* Arg Count */
	XrmValue from_value, to_value; /* For resource conversion */
	XtPointer tmp_value;             /* ditto */
	int fg, bg;                    /* colour values for pixmaps */ 
	XmString *list_items;          /* For list items */
	int list_item;                 /* Index for list_items */
	Atom *atom_list;               /* For Drop Site targets */
	XmString xmstrings[16];    /* temporary storage for XmStrings */
	Widget widget1 = (Widget)NULL;

	XtSetArg(al[ac], XmNallowShellResize, TRUE); ac++;
	XtSetArg(al[ac], XmNx, 300); ac++;
	XtSetArg(al[ac], XmNy, 300); ac++;
	XtSetArg(al[ac], XmNargc, app_argc); ac++;
	XtSetArg(al[ac], XmNargv, app_argv); ac++;
	toplevel = XtAppCreateShell ( app_name, "XGpop", applicationShellWidgetClass, display, al, ac );
	ac = 0;
	XtSetArg(al[ac], XmNautoUnmanage, FALSE); ac++;
	widget1 = XmCreateForm ( toplevel, "widget1", al, ac );
	ac = 0;
	XtSetArg(al[ac], XmNx, 5); ac++;
	XtSetArg(al[ac], XmNy, 19); ac++;
	XtSetArg(al[ac], XmNmarginLeft, 25); ac++;
	XtSetArg(al[ac], XmNmarginRight, 25); ac++;
	LLmsg = XmCreateLabel ( widget1, "LLmsg", al, ac );
	ac = 0;
	XtSetArg(al[ac], XmNx, 20); ac++;
	XtSetArg(al[ac], XmNy, 57); ac++;
	XtSetArg(al[ac], XmNmarginTop, 5); ac++;
	XtSetArg(al[ac], XmNmarginBottom, 5); ac++;
	XtSetArg(al[ac], XmNmarginLeft, 5); ac++;
	XtSetArg(al[ac], XmNmarginRight, 5); ac++;
	BT1 = XmCreatePushButton ( widget1, "BT1", al, ac );
	ac = 0;
	XtSetArg(al[ac], XmNx, 98); ac++;
	XtSetArg(al[ac], XmNy, 57); ac++;
	XtSetArg(al[ac], XmNmarginTop, 5); ac++;
	XtSetArg(al[ac], XmNmarginBottom, 5); ac++;
	XtSetArg(al[ac], XmNmarginLeft, 5); ac++;
	XtSetArg(al[ac], XmNmarginRight, 5); ac++;
	BT2 = XmCreatePushButton ( widget1, "BT2", al, ac );
	ac = 0;
	XtSetArg(al[ac], XmNx, 255); ac++;
	XtSetArg(al[ac], XmNy, 57); ac++;
	XtSetArg(al[ac], XmNmarginTop, 5); ac++;
	XtSetArg(al[ac], XmNmarginBottom, 5); ac++;
	XtSetArg(al[ac], XmNmarginLeft, 5); ac++;
	XtSetArg(al[ac], XmNmarginRight, 5); ac++;
	BT3 = XmCreatePushButton ( widget1, "BT3", al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNtopOffset, 19); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 5); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, 5); ac++;
	XtSetValues ( LLmsg,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_WIDGET); ac++;
	XtSetArg(al[ac], XmNtopOffset, 20); ac++;
	XtSetArg(al[ac], XmNtopWidget, LLmsg); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNbottomOffset, 20); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 20); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
	XtSetValues ( BT1,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_OPPOSITE_WIDGET); ac++;
	XtSetArg(al[ac], XmNtopWidget, BT1); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_WIDGET); ac++;
	XtSetArg(al[ac], XmNleftOffset, 20); ac++;
	XtSetArg(al[ac], XmNleftWidget, BT1); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
	XtSetValues ( BT2,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_OPPOSITE_WIDGET); ac++;
	XtSetArg(al[ac], XmNtopWidget, BT2); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, 20); ac++;
	XtSetValues ( BT3,al, ac );
	ac = 0;
	XtAddCallback (BT1, XmNactivateCallback, BTactivateCb,1);
	XtAddCallback (BT2, XmNactivateCallback, BTactivateCb,2);
	XtAddCallback (BT3, XmNactivateCallback, BTactivateCb,3);
	children[ac++] = LLmsg;
	children[ac++] = BT1;
	children[ac++] = BT2;
	children[ac++] = BT3;
	XtManageChildren(children, ac);
	ac = 0;
	XtManageChild ( widget1);
}



XtAppContext app_context;
Display *display;       /*  Display             */

static void gpop_init(int argc, char **argv)
{
	XmString chaineMotif;
	int nbBoutons=(argc-2)/2;

	chaineMotif=XmStringCreateSimple(argv[1]);
	XtVaSetValues(LLmsg, XmNlabelString, chaineMotif, NULL);
	XmStringFree(chaineMotif);

	if(nbBoutons>=1)
	{
		sscanf(argv[3], "%d", &(tab_cr[1]));
		chaineMotif=XmStringCreateSimple(argv[4]);
		XtVaSetValues(BT1, XmNlabelString, chaineMotif, NULL);
		XmStringFree(chaineMotif);
	}
	else
		XtUnmanageChild(BT1);

	if(nbBoutons>=2)
	{
		sscanf(argv[5], "%d", &(tab_cr[2]));
		chaineMotif=XmStringCreateSimple(argv[6]);
		XtVaSetValues(BT2, XmNlabelString, chaineMotif, NULL);
		XmStringFree(chaineMotif);
	}
	else
		XtUnmanageChild(BT2);

	if(nbBoutons>=3)
	{
		sscanf(argv[7], "%d", &(tab_cr[3]));
		chaineMotif=XmStringCreateSimple(argv[8]);
		XtVaSetValues(BT3, XmNlabelString, chaineMotif, NULL);
		XmStringFree(chaineMotif);
	}
	else
		XtUnmanageChild(BT3);
}

int main (int argc, char **argv)
{
	if (argc<5)
	{
	    printf("%s: Bad argument count, exiting...\n", argv[0]);
	    exit (-1);
	}
	XtSetLanguageProc ( (XtAppContext) NULL, (XtLanguageProc) NULL, (XtPointer) NULL );
	XtToolkitInitialize ();
	app_context = XtCreateApplicationContext ();
	display = XtOpenDisplay (app_context, argv[2], "Message", "XGpop",
	                         NULL, 0, &argc, argv);
	if (!display)
	{
	    printf("%s: can't open display, exiting...\n", argv[0]);
	    exit (-1);
	}
	create_toplevel ( display, argv[0], argc, argv );
	XtRealizeWidget (toplevel);
	gpop_init(argc, argv);
	XtAppMainLoop (app_context);
	exit (0);
}

