/*E*/
/*Fichier : $Id: scon_dir.c,v 1.8 1997/12/23 16:04:49 milleville Exp $      Release : $Revision: 1.8 $        Date : $Date: 1997/12/23 16:04:49 $
------------------------------------------------------
* STERIA *  PROJET MIGRAZUR 
------------------------------------------------------
* SOUS-SYSTEME  TSCONF
------------------------------------------------------
* MODULE SCON_DIR * FICHIER scon_dir.c
------------------------------------------------------
* DESCRIPTION DU MODULE :
*
* Ce module est le module principal de la tache TSCONF
*	Il permet de declarer toutes les callbacks 
*	associes a l'interface Homme-Machine et affiche
*	celle-ci.
*
------------------------------------------------------
* HISTORIQUE :
*
* T.Milleville	30 Aug 1994	: Creation
* T.Milleville	09 Avr 1995	: Ajout Tache Shell Script V1.5
* T.Milleville	25 Jul 1995	: Mise a jour entete V1.6
* P.Niepceron	22 Aou 1995	: Ajout PC simplifie v1.7
* P.Niepceron   16 Dec 1997	: Ajout PC2 1.11
------------------------------------------------------*/

/* fichiers inclus */

#include <xzsem.h>
#include "scon_ser.h"
#include "scon_var.h"
#include "scon_dir.h"

/*
** Generated by X-Designer 
*/
/*
**LIBS: -lMrm -lXm -lXt -lX11
*/

#include <X11/Xatom.h>
#include <X11/Intrinsic.h>
#include <X11/Shell.h>

#include <Mrm/MrmAppl.h>
#include <Mrm/MrmPublic.h>
#include <Xm/Xm.h>
#include <Xm/CascadeB.h>
#include <Xm/DialogS.h>
#include <Xm/Form.h>
#include <Xm/Label.h>
#include <Xm/PushB.h>
#include <Xm/RowColumn.h>
#include <Xm/Separator.h>
#include <Xm/TextF.h>
#include <Xm/ToggleBG.h>
#include <stdio.h>

/* definitions de constantes */

#define  Titre_BDMAC  "Caracteristiques Machine "
#define  Titre_BDCOMA  "Copie d'une Machine "
#define  Titre_BDCMA  "Creation-Destruction d'une Machine"
#define  Titre_BDCTM  "Creation-Destruction d'une Tache"
#define  Titre_BDSIT  "Ajout-Suppression d'un Site"
#define  Titre_BDCAL  "Ajout-Suppression d'un Calculateur"
#define  Titre_BDSSY  "Ajout-Suppression d'un Sous-Systeme"
#define  Titre_BDENT  "Ajout--Suppression d'une Entite"
#define  Titre_BDCJA  "Creation Journal d'Administartion"
#define  Titre_BDERR  "Erreur"
#define  Titre_BDCON1  "Confirmation"
#define  Titre_BDCON2  "Confirmation"
#define  Titre_BDTAS  "Creation d'une Tache"
#define  Titre_BDTAC  "Destruction d'une Tache "

/* definitions de types locaux */

/* definition de macro locales */

/* declaration de variables locales */

static char *version = "$Id: scon_dir.c,v 1.8 1997/12/23 16:04:49 milleville Exp $ : scon_dir" ;


extern void BDCAL_VAL (Widget, XtPointer, XtPointer );
extern void BDSSY_VAL (Widget, XtPointer, XtPointer );
extern void BDENT_VAL (Widget, XtPointer, XtPointer );
extern void PERI_ARM_CB (Widget, XtPointer, XtPointer );
extern void AUTR_ARM_CB (Widget, XtPointer, XtPointer );
extern void TACH_ARM_CB (Widget, XtPointer, XtPointer );
extern void BDTAS_VAL (Widget, XtPointer, XtPointer );
extern void BDSIT_VAL (Widget, XtPointer, XtPointer );
extern void BDCON1_VAL (Widget, XtPointer, XtPointer );
extern void BDCON2_VAL (Widget, XtPointer, XtPointer );
extern void BDCJA_VAL (Widget, XtPointer, XtPointer );
extern void BDCTM_VAL (Widget, XtPointer, XtPointer );
extern void BDCMA_VAL (Widget, XtPointer, XtPointer );
extern void BDCOMA_VAL (Widget, XtPointer, XtPointer );
extern void BDTAC_VAL (Widget, XtPointer, XtPointer );
extern void BDMAC_VAL (Widget, XtPointer, XtPointer );
extern void BDMAC_QUI (Widget, XtPointer, XtPointer );
extern void CreMac_CB (Widget, XtPointer, XtPointer );
extern void CoMac_CB (Widget, XtPointer, XtPointer );
extern void DesMac_CB (Widget, XtPointer, XtPointer );
extern void CreTac_CB (Widget, XtPointer, XtPointer );
extern void DesTac_CB (Widget, XtPointer, XtPointer );
extern void CreSitFad_CB (Widget, XtPointer, XtPointer );
extern void CreMacFad_CB (Widget, XtPointer, XtPointer );
extern void CreSsyFad_CB (Widget, XtPointer, XtPointer );
extern void CreTacFad_CB (Widget, XtPointer, XtPointer );
extern void CreEntFad_CB (Widget, XtPointer, XtPointer );
extern void DesSitFad_CB (Widget, XtPointer, XtPointer );
extern void DesMacFad_CB (Widget, XtPointer, XtPointer );
extern void DesSsyFad_CB (Widget, XtPointer, XtPointer );
extern void DesTacFad_CB (Widget, XtPointer, XtPointer );
extern void DesEntFad_CB (Widget, XtPointer, XtPointer );
extern void CreJou_CB (Widget, XtPointer, XtPointer );
extern void CONFM_QUI (Widget, XtPointer, XtPointer );

static MRMRegisterArg reglist[] = {
	{"BDCAL_VAL",(XtPointer) BDCAL_VAL},
	{"BDSSY_VAL",(XtPointer) BDSSY_VAL},
	{"BDENT_VAL",(XtPointer) BDENT_VAL},
	{"PERI_ARM_CB",(XtPointer) PERI_ARM_CB},
	{"AUTR_ARM_CB",(XtPointer) AUTR_ARM_CB},
	{"TACH_ARM_CB",(XtPointer) TACH_ARM_CB},
	{"BDTAS_VAL",(XtPointer) BDTAS_VAL},
	{"BDSIT_VAL",(XtPointer) BDSIT_VAL},
	{"BDCON1_VAL",(XtPointer) BDCON1_VAL},
	{"BDCON2_VAL",(XtPointer) BDCON2_VAL},
	{"BDCJA_VAL",(XtPointer) BDCJA_VAL},
	{"BDCTM_VAL",(XtPointer) BDCTM_VAL},
	{"BDCMA_VAL",(XtPointer) BDCMA_VAL},
	{"BDCOMA_VAL",(XtPointer) BDCOMA_VAL},
	{"BDTAC_VAL",(XtPointer) BDTAC_VAL},
	{"BDMAC_VAL",(XtPointer) BDMAC_VAL},
	{"BDMAC_QUI",(XtPointer) BDMAC_QUI},
	{"CreMac_CB",(XtPointer) CreMac_CB},
	{"CoMac_CB",(XtPointer) CoMac_CB},
	{"DesMac_CB",(XtPointer) DesMac_CB},
	{"CreTac_CB",(XtPointer) CreTac_CB},
	{"DesTac_CB",(XtPointer) DesTac_CB},
	{"CreSitFad_CB",(XtPointer) CreSitFad_CB},
	{"CreMacFad_CB",(XtPointer) CreMacFad_CB},
	{"CreSsyFad_CB",(XtPointer) CreSsyFad_CB},
	{"CreTacFad_CB",(XtPointer) CreTacFad_CB},
	{"CreEntFad_CB",(XtPointer) CreEntFad_CB},
	{"DesSitFad_CB",(XtPointer) DesSitFad_CB},
	{"DesMacFad_CB",(XtPointer) DesMacFad_CB},
	{"DesSsyFad_CB",(XtPointer) DesSsyFad_CB},
	{"DesTacFad_CB",(XtPointer) DesTacFad_CB},
	{"DesEntFad_CB",(XtPointer) DesEntFad_CB},
	{"CreJou_CB",(XtPointer) CreJou_CB},
	{"CONFM_QUI",(XtPointer) CONFM_QUI},
};

static int reglist_num = (sizeof(reglist)/sizeof( MRMRegisterArg));

XtAppContext app_context;
Display *display;       /*  Display             */

static char *mrm_filename_list[] = {"scon_fr.uid"};

/* declaration de fonctions internes */

/* definition de fonctions externes */

 


void XDmanage_link (Widget w, XtPointer client_data, XtPointer call_data)
{
    XtManageChild ( *(Widget *)client_data );
}

void XDunmanage_link (Widget w, XtPointer client_data, XtPointer call_data)
{
    XtUnmanageChild ( *(Widget *)client_data );
}

void XDpopup_link (Widget w, XtPointer client_data, XtPointer call_data)
{
    XtPopup ( *(Widget *)client_data, XtGrabNone );
}

void XDpopdown_link (Widget w, XtPointer client_data, XtPointer call_data)
{
    XtPopdown ( *(Widget *)client_data );
}

void XDmap_link (Widget w, XtPointer client_data, XtPointer call_data)
{
    XtMapWidget (*(Widget *)client_data);
}

void XDunmap_link (Widget w, XtPointer client_data, XtPointer call_data)
{
    XtUnmapWidget (*(Widget *)client_data);
}

void XDenable_link (Widget w, XtPointer client_data, XtPointer call_data)
{
    XtSetSensitive (*(Widget *)client_data, TRUE);
}

void XDdisable_link (Widget w, XtPointer client_data, XtPointer call_data)
{
    XtSetSensitive (*(Widget *)client_data, FALSE);
}


void create_BDCAL (Widget parent, MrmHierarchy hierarchy_id, MrmCode *mrm_vg_class)
{
	Display *display = XtDisplay ( parent );
	Widget children[4];      /* Children to manage */
	Arg al[64];                    /* Arg List */
	register int ac = 0;           /* Arg Count */
	XrmValue from_value, to_value; /* For resource conversion */
	XtPointer tmp_value;             /* ditto */
	int fg, bg;                    /* colour values for pixmaps */ 
	XmString *list_items;          /* For list items */
	int list_item;                 /* Index for list_items */
	Atom *atom_list;               /* For Drop Site targets */
	XmString xmstrings[16];    /* temporary storage for XmStrings */
	Widget widget4 = (Widget)NULL;

	BDCAL = XmCreateDialogShell ( parent, Titre_BDCAL, al, ac );
	(void) MrmFetchWidget ( hierarchy_id, "BDCAL_FM", BDCAL, &BDCAL_FM, mrm_vg_class );
	BDCAL_CH_CAL = XtNameToWidget ( BDCAL_FM, "BDCAL_CH_CAL" );
	widget4 = XtNameToWidget ( BDCAL_FM, "widget4" );
	XtAddCallback (widget4,XmNactivateCallback, XDunmanage_link, (XtPointer) &BDCAL_FM );




}


void create_BDSSY (Widget parent, MrmHierarchy hierarchy_id, MrmCode *mrm_vg_class)
{
	Display *display = XtDisplay ( parent );
	Widget children[6];      /* Children to manage */
	Arg al[64];                    /* Arg List */
	register int ac = 0;           /* Arg Count */
	XrmValue from_value, to_value; /* For resource conversion */
	XtPointer tmp_value;             /* ditto */
	int fg, bg;                    /* colour values for pixmaps */ 
	XmString *list_items;          /* For list items */
	int list_item;                 /* Index for list_items */
	Atom *atom_list;               /* For Drop Site targets */
	XmString xmstrings[16];    /* temporary storage for XmStrings */
	Widget widget11 = (Widget)NULL;
	Widget widget13 = (Widget)NULL;

	BDSSY = XmCreateDialogShell ( parent, Titre_BDSSY, al, ac );
	(void) MrmFetchWidget ( hierarchy_id, "BDSSY_FM", BDSSY, &BDSSY_FM, mrm_vg_class );
	BDSSY_CH_SSY = XtNameToWidget ( BDSSY_FM, "BDSSY_CH_SSY" );
	widget11 = XtNameToWidget ( BDSSY_FM, "widget11" );
	XtAddCallback (widget11,XmNactivateCallback, XDunmanage_link, (XtPointer) &BDSSY_FM );
	widget13 = XtNameToWidget ( BDSSY_FM, "widget13" );
	BDSSY_TO_ST = XtNameToWidget ( widget13, "BDSSY_TO_ST" );
	BDSSY_TO_SD = XtNameToWidget ( widget13, "BDSSY_TO_SD" );
	BDSSY_TO_SC = XtNameToWidget ( widget13, "BDSSY_TO_SC" );
	BDSSY_TO_LT = XtNameToWidget ( widget13, "BDSSY_TO_LT" );
	BDSSY_TO_SP = XtNameToWidget ( widget13, "BDSSY_TO_SP" );
	BDSSY_TO_PCS = XtNameToWidget ( widget13, "BDSSY_TO_PCS" );
	BDSSY_TO_PC2 = XtNameToWidget ( widget13, "BDSSY_TO_PC2" );
	BDSSY_TO_PC2LT = XtNameToWidget ( widget13, "BDSSY_TO_PC2LT");






}


void create_BDENT (Widget parent, MrmHierarchy hierarchy_id, MrmCode *mrm_vg_class)
{
	Display *display = XtDisplay ( parent );
	Widget children[12];      /* Children to manage */
	Arg al[64];                    /* Arg List */
	register int ac = 0;           /* Arg Count */
	XrmValue from_value, to_value; /* For resource conversion */
	XtPointer tmp_value;             /* ditto */
	int fg, bg;                    /* colour values for pixmaps */ 
	XmString *list_items;          /* For list items */
	int list_item;                 /* Index for list_items */
	Atom *atom_list;               /* For Drop Site targets */
	XmString xmstrings[16];    /* temporary storage for XmStrings */
	Widget widget20 = (Widget)NULL;
	Widget widget24 = (Widget)NULL;

	BDENT = XmCreateDialogShell ( parent, Titre_BDENT, al, ac );
	(void) MrmFetchWidget ( hierarchy_id, "BDENT_FM", BDENT, &BDENT_FM, mrm_vg_class );
	widget20 = XtNameToWidget ( BDENT_FM, "widget20" );
	XtAddCallback (widget20,XmNactivateCallback, XDunmanage_link, (XtPointer) &BDENT_FM );
	BDENT_LA_SI = XtNameToWidget ( BDENT_FM, "BDENT_LA_SI" );
	BDENT_CH_SI = XtNameToWidget ( BDENT_FM, "BDENT_CH_SI" );
	widget24 = XtNameToWidget ( BDENT_FM, "widget24" );
	BDENT_TO_PER = XtNameToWidget ( widget24, "BDENT_TO_PER" );
	BDENT_TO_INT = XtNameToWidget ( widget24, "BDENT_TO_INT" );
	BDENT_TO_CON = XtNameToWidget ( widget24, "BDENT_TO_CON" );
	BDENT_TO_TAC = XtNameToWidget ( widget24, "BDENT_TO_TAC" );
	BDENT_LA_TA = XtNameToWidget ( BDENT_FM, "BDENT_LA_TA" );
	BDENT_CH_TA = XtNameToWidget ( BDENT_FM, "BDENT_CH_TA" );
	BDENT_LA_CA = XtNameToWidget ( BDENT_FM, "BDENT_LA_CA" );
	BDENT_CH_CA = XtNameToWidget ( BDENT_FM, "BDENT_CH_CA" );
	BDENT_LA_EN = XtNameToWidget ( BDENT_FM, "BDENT_LA_EN" );
	BDENT_CH_EN = XtNameToWidget ( BDENT_FM, "BDENT_CH_EN" );

}


void create_BDTAS (Widget parent, MrmHierarchy hierarchy_id, MrmCode *mrm_vg_class)
{
	Display *display = XtDisplay ( parent );
	Widget children[8];      /* Children to manage */
	Arg al[64];                    /* Arg List */
	register int ac = 0;           /* Arg Count */
	XrmValue from_value, to_value; /* For resource conversion */
	XtPointer tmp_value;             /* ditto */
	int fg, bg;                    /* colour values for pixmaps */ 
	XmString *list_items;          /* For list items */
	int list_item;                 /* Index for list_items */
	Atom *atom_list;               /* For Drop Site targets */
	XmString xmstrings[16];    /* temporary storage for XmStrings */
	Widget widget41 = (Widget)NULL;
	Widget widget43 = (Widget)NULL;

	BDTAS = XmCreateDialogShell ( parent, Titre_BDTAS, al, ac );
	(void) MrmFetchWidget ( hierarchy_id, "BDTAS_FM", BDTAS, &BDTAS_FM, mrm_vg_class );
	BDTAS_CH_SSY = XtNameToWidget ( BDTAS_FM, "BDTAS_CH_SSY" );
	BDTAS_CH_TAC = XtNameToWidget ( BDTAS_FM, "BDTAS_CH_TAC" );
	widget41 = XtNameToWidget ( BDTAS_FM, "widget41" );
	XtAddCallback (widget41,XmNactivateCallback, XDunmanage_link, (XtPointer) &BDTAS_FM );
	widget43 = XtNameToWidget ( BDTAS_FM, "widget43" );
	BDTAS_TO_ST = XtNameToWidget ( widget43, "BDTAS_TO_ST" );
	BDTAS_TO_SD = XtNameToWidget ( widget43, "BDTAS_TO_SD" );
	BDTAS_TO_SC = XtNameToWidget ( widget43, "BDTAS_TO_SC" );
	BDTAS_TO_LT = XtNameToWidget ( widget43, "BDTAS_TO_LT" );
	BDTAS_TO_SP = XtNameToWidget ( widget43, "BDTAS_TO_SP" );
	BDTAS_TO_PCS = XtNameToWidget ( widget43, "BDTAS_TO_PCS" );
	BDTAS_TO_PC2 = XtNameToWidget ( widget43, "BDTAS_TO_PC2");
	BDTAS_TO_PC2LT = XtNameToWidget ( widget43, "BDTAS_TO_PC2LT");

	Radio_TypeTache = XtNameToWidget (BDTAS_FM, "Radio_TypeTache");
	Tache_Permanente = XtNameToWidget ( Radio_TypeTache, 
						"Tache_Permanente" );
	Tache_Temporaire = XtNameToWidget ( Radio_TypeTache, 
						"Tache_Temporaire" );
	Tache_ShellScript = XtNameToWidget ( Radio_TypeTache, 
						"Tache_ShellScript" );
}


void create_BDSIT (Widget parent, MrmHierarchy hierarchy_id, MrmCode *mrm_vg_class)
{
	Display *display = XtDisplay ( parent );
	Widget children[4];      /* Children to manage */
	Arg al[64];                    /* Arg List */
	register int ac = 0;           /* Arg Count */
	XrmValue from_value, to_value; /* For resource conversion */
	XtPointer tmp_value;             /* ditto */
	int fg, bg;                    /* colour values for pixmaps */ 
	XmString *list_items;          /* For list items */
	int list_item;                 /* Index for list_items */
	Atom *atom_list;               /* For Drop Site targets */
	XmString xmstrings[16];    /* temporary storage for XmStrings */
	Widget widget52 = (Widget)NULL;

	BDSIT = XmCreateDialogShell ( parent, Titre_BDSIT, al, ac );
	(void) MrmFetchWidget ( hierarchy_id, "BDSIT_FM", BDSIT, &BDSIT_FM, mrm_vg_class );
	BDSIT_CH_SIT = XtNameToWidget ( BDSIT_FM, "BDSIT_CH_SIT" );
	widget52 = XtNameToWidget ( BDSIT_FM, "widget52" );
	XtAddCallback (widget52,XmNactivateCallback, XDunmanage_link, (XtPointer) &BDSIT_FM );


}


void create_BDCON1 (Widget parent, MrmHierarchy hierarchy_id, MrmCode *mrm_vg_class)
{
	Display *display = XtDisplay ( parent );
	Widget children[3];      /* Children to manage */
	Arg al[64];                    /* Arg List */
	register int ac = 0;           /* Arg Count */
	XrmValue from_value, to_value; /* For resource conversion */
	XtPointer tmp_value;             /* ditto */
	int fg, bg;                    /* colour values for pixmaps */ 
	XmString *list_items;          /* For list items */
	int list_item;                 /* Index for list_items */
	Atom *atom_list;               /* For Drop Site targets */
	XmString xmstrings[16];    /* temporary storage for XmStrings */
	Widget widget58 = (Widget)NULL;

	BDCON1 = XmCreateDialogShell ( parent, Titre_BDCON1, al, ac );
	(void) MrmFetchWidget ( hierarchy_id, "BDCON1_FM", BDCON1, &BDCON1_FM, mrm_vg_class );
	BDCON1_LA = XtNameToWidget ( BDCON1_FM, "BDCON1_LA" );
	widget58 = XtNameToWidget ( BDCON1_FM, "widget58" );
	XtAddCallback (widget58,XmNactivateCallback, XDunmanage_link, (XtPointer) &BDCON1_FM );


}


void create_BDCON2 (Widget parent, MrmHierarchy hierarchy_id, MrmCode *mrm_vg_class)
{
	Display *display = XtDisplay ( parent );
	Widget children[3];      /* Children to manage */
	Arg al[64];                    /* Arg List */
	register int ac = 0;           /* Arg Count */
	XrmValue from_value, to_value; /* For resource conversion */
	XtPointer tmp_value;             /* ditto */
	int fg, bg;                    /* colour values for pixmaps */ 
	XmString *list_items;          /* For list items */
	int list_item;                 /* Index for list_items */
	Atom *atom_list;               /* For Drop Site targets */
	XmString xmstrings[16];    /* temporary storage for XmStrings */
	Widget widget63 = (Widget)NULL;

	BDCON2 = XmCreateDialogShell ( parent, Titre_BDCON2, al, ac );
	(void) MrmFetchWidget ( hierarchy_id, "BDCON2_FM", BDCON2, &BDCON2_FM, mrm_vg_class );
	BDCON2_LA = XtNameToWidget ( BDCON2_FM, "BDCON2_LA" );
	widget63 = XtNameToWidget ( BDCON2_FM, "widget63" );
	XtAddCallback (widget63,XmNactivateCallback, XDunmanage_link, (XtPointer) &BDCON2_FM );


}


void create_BDCJA (Widget parent, MrmHierarchy hierarchy_id, MrmCode *mrm_vg_class)
{
	Display *display = XtDisplay ( parent );
	Widget children[4];      /* Children to manage */
	Arg al[64];                    /* Arg List */
	register int ac = 0;           /* Arg Count */
	XrmValue from_value, to_value; /* For resource conversion */
	XtPointer tmp_value;             /* ditto */
	int fg, bg;                    /* colour values for pixmaps */ 
	XmString *list_items;          /* For list items */
	int list_item;                 /* Index for list_items */
	Atom *atom_list;               /* For Drop Site targets */
	XmString xmstrings[16];    /* temporary storage for XmStrings */
	Widget widget69 = (Widget)NULL;

	BDCJA = XmCreateDialogShell ( parent, Titre_BDCJA, al, ac );
	(void) MrmFetchWidget ( hierarchy_id, "BDCJA_FM", BDCJA, &BDCJA_FM, mrm_vg_class );
	BDCJA_CH_TAI = XtNameToWidget ( BDCJA_FM, "BDCJA_CH_TAI" );
	widget69 = XtNameToWidget ( BDCJA_FM, "widget69" );
	XtAddCallback (widget69,XmNactivateCallback, XDunmanage_link, (XtPointer) &BDCJA_FM );



}


void create_BDERR (Widget parent, MrmHierarchy hierarchy_id, MrmCode *mrm_vg_class)
{
	Display *display = XtDisplay ( parent );
	Widget children[2];      /* Children to manage */
	Arg al[64];                    /* Arg List */
	register int ac = 0;           /* Arg Count */
	XrmValue from_value, to_value; /* For resource conversion */
	XtPointer tmp_value;             /* ditto */
	int fg, bg;                    /* colour values for pixmaps */ 
	XmString *list_items;          /* For list items */
	int list_item;                 /* Index for list_items */
	Atom *atom_list;               /* For Drop Site targets */
	XmString xmstrings[16];    /* temporary storage for XmStrings */
	Widget widget73 = (Widget)NULL;

	BDERR = XmCreateDialogShell ( parent, Titre_BDERR, al, ac );
	(void) MrmFetchWidget ( hierarchy_id, "BDERR_FM", BDERR, &BDERR_FM, mrm_vg_class );
	BDERR_LA = XtNameToWidget ( BDERR_FM, "BDERR_LA" );
	widget73 = XtNameToWidget ( BDERR_FM, "widget73" );
	XtAddCallback (widget73,XmNactivateCallback, XDunmanage_link, (XtPointer) &BDERR_FM );


}


void create_BDCTM (Widget parent, MrmHierarchy hierarchy_id, MrmCode *mrm_vg_class)
{
	Display *display = XtDisplay ( parent );
	Widget children[6];      /* Children to manage */
	Arg al[64];                    /* Arg List */
	register int ac = 0;           /* Arg Count */
	XrmValue from_value, to_value; /* For resource conversion */
	XtPointer tmp_value;             /* ditto */
	int fg, bg;                    /* colour values for pixmaps */ 
	XmString *list_items;          /* For list items */
	int list_item;                 /* Index for list_items */
	Atom *atom_list;               /* For Drop Site targets */
	XmString xmstrings[16];    /* temporary storage for XmStrings */
	Widget widget80 = (Widget)NULL;

	BDCTM = XmCreateDialogShell ( parent, Titre_BDCTM, al, ac );
	(void) MrmFetchWidget ( hierarchy_id, "BDCTM_FM", BDCTM, &BDCTM_FM, mrm_vg_class );
	BDCTM_CH_CAL = XtNameToWidget ( BDCTM_FM, "BDCTM_CH_CAL" );
	BDCTM_CH_TAC = XtNameToWidget ( BDCTM_FM, "BDCTM_CH_TAC" );
	widget80 = XtNameToWidget ( BDCTM_FM, "widget80" );
	XtAddCallback (widget80,XmNactivateCallback, XDunmanage_link, (XtPointer) &BDCTM_FM );


}


void create_BDCMA (Widget parent, MrmHierarchy hierarchy_id, MrmCode *mrm_vg_class)
{
	Display *display = XtDisplay ( parent );
	Widget children[4];      /* Children to manage */
	Arg al[64];                    /* Arg List */
	register int ac = 0;           /* Arg Count */
	XrmValue from_value, to_value; /* For resource conversion */
	XtPointer tmp_value;             /* ditto */
	int fg, bg;                    /* colour values for pixmaps */ 
	XmString *list_items;          /* For list items */
	int list_item;                 /* Index for list_items */
	Atom *atom_list;               /* For Drop Site targets */
	XmString xmstrings[16];    /* temporary storage for XmStrings */
	Widget widget86 = (Widget)NULL;

	BDCMA = XmCreateDialogShell ( parent, Titre_BDCMA, al, ac );
	(void) MrmFetchWidget ( hierarchy_id, "BDCMA_FM", BDCMA, &BDCMA_FM, mrm_vg_class );
	BDCMA_CH_CAL = XtNameToWidget ( BDCMA_FM, "BDCMA_CH_CAL" );
	widget86 = XtNameToWidget ( BDCMA_FM, "widget86" );
	XtAddCallback (widget86,XmNactivateCallback, XDunmanage_link, (XtPointer) &BDCMA_FM );


}

void create_BDCOMA (Widget parent, MrmHierarchy hierarchy_id, MrmCode *mrm_vg_class)
{
	Display *display = XtDisplay ( parent );
	Widget children[4];      /* Children to manage */
	Arg al[64];                    /* Arg List */
	register int ac = 0;           /* Arg Count */
	XrmValue from_value, to_value; /* For resource conversion */
	XtPointer tmp_value;             /* ditto */
	int fg, bg;                    /* colour values for pixmaps */ 
	XmString *list_items;          /* For list items */
	int list_item;                 /* Index for list_items */
	Atom *atom_list;               /* For Drop Site targets */
	XmString xmstrings[16];    /* temporary storage for XmStrings */
	Widget widgetNOK = (Widget)NULL;


	BDCOMA = XmCreateDialogShell ( parent, Titre_BDCOMA, al, ac );
	(void) MrmFetchWidget ( hierarchy_id, "BDCOMA_FM", 
					BDCOMA, &BDCOMA_FM, mrm_vg_class );
	BDCOMA_CH_CAL_DEST = 
		XtNameToWidget ( BDCOMA_FM, "BDCOMA_CH_CAL_DEST" );
	BDCOMA_CH_CAL_EXPED = 
		XtNameToWidget ( BDCOMA_FM, "BDCOMA_CH_CAL_EXPED" );

	widgetNOK = XtNameToWidget ( BDCOMA_FM, "widgetNOK" );
	XtAddCallback (widgetNOK,XmNactivateCallback, 
		XDunmanage_link, (XtPointer) &BDCOMA_FM );
}


void create_BDTAC (Widget parent, MrmHierarchy hierarchy_id, MrmCode *mrm_vg_class)
{
	Display *display = XtDisplay ( parent );
	Widget children[4];      /* Children to manage */
	Arg al[64];                    /* Arg List */
	register int ac = 0;           /* Arg Count */
	XrmValue from_value, to_value; /* For resource conversion */
	XtPointer tmp_value;             /* ditto */
	int fg, bg;                    /* colour values for pixmaps */ 
	XmString *list_items;          /* For list items */
	int list_item;                 /* Index for list_items */
	Atom *atom_list;               /* For Drop Site targets */
	XmString xmstrings[16];    /* temporary storage for XmStrings */
	Widget widget95 = (Widget)NULL;
	Widget widget101 = (Widget)NULL;

	BDTAC = XmCreateDialogShell ( parent, Titre_BDTAS, al, ac );
	(void) MrmFetchWidget ( hierarchy_id, "BDTAC_FM", BDTAC, &BDTAC_FM, mrm_vg_class );
	widget95 = XtNameToWidget ( BDTAC_FM, "widget95" );
	BDTAC_CH_TAC = XtNameToWidget ( widget95, "BDTAC_CH_TAC" );
	BDTAC_CH_LRT = XtNameToWidget ( widget95, "BDTAC_CH_LRT" );
	BDTAC_CH_LRL = XtNameToWidget ( widget95, "BDTAC_CH_LRL" );
	BDTAC_CH_TAI = XtNameToWidget ( widget95, "BDTAC_CH_TAI" );
	widget101 = XtNameToWidget ( BDTAC_FM, "widget101" );
	XtAddCallback (widget101,XmNactivateCallback, XDunmanage_link, (XtPointer) &BDTAC_FM );



}


void create_BDMAC (Widget parent, MrmHierarchy hierarchy_id, MrmCode *mrm_vg_class)
{


	Display *display = XtDisplay ( parent );
	Widget children[10];      /* Children to manage */
	Arg al[64];                    /* Arg List */
	register int ac = 0;           /* Arg Count */
	XrmValue from_value, to_value; /* For resource conversion */
	XtPointer tmp_value;             /* ditto */
	int fg, bg;                    /* colour values for pixmaps */ 
	XmString *list_items;          /* For list items */
	int list_item;                 /* Index for list_items */
	Atom *atom_list;               /* For Drop Site targets */
	XmString xmstrings[16];    /* temporary storage for XmStrings */
	Widget widget108 = (Widget)NULL;
	Widget widget121 = (Widget)NULL;
	Widget widget131 = (Widget)NULL;
	Widget widget134 = (Widget)NULL;
	Widget widget138 = (Widget)NULL;
	Widget Type_Profil = (Widget)NULL;

	BDMAC = XmCreateDialogShell ( parent, Titre_BDMAC, al, ac );
	(void) MrmFetchWidget ( hierarchy_id, "BDMAC_FM", BDMAC, &BDMAC_FM, mrm_vg_class );
	
	widget108 = XtNameToWidget ( BDMAC_FM, "widget108" );
	BDMAC_CH_MAC = XtNameToWidget ( widget108, "BDMAC_CH_MAC" );
	BDMAC_CH_SIT = XtNameToWidget ( widget108, "BDMAC_CH_SIT" );
	BDMAC_CH_PSR = XtNameToWidget ( widget108, "BDMAC_CH_PSR" );
	widget121 = XtNameToWidget ( BDMAC_FM, "widget121" );
	BDMAC_CH_ECR = XtNameToWidget ( widget121, "BDMAC_CH_ECR" );
	BDMAC_CH_IMP = XtNameToWidget ( widget121, "BDMAC_CH_IMP" );
	BDMAC_CH_MIM = XtNameToWidget ( widget121, "BDMAC_CH_MIM" );
	BDMAC_CH_IMPSEC = XtNameToWidget ( widget121, "BDMAC_CH_IMPSEC" );
	/*BDMAC_CH_TRA = XtNameToWidget ( widget121, "BDMAC_CH_TRA" );
	BDMAC_CH_MTR = XtNameToWidget ( widget121, "BDMAC_CH_MTR" );*/
	BDMAC_CH_CHE = XtNameToWidget ( widget121, "BDMAC_CH_CHE" );
	BDMAC_CH_TAI = XtNameToWidget ( widget121, "BDMAC_CH_TAI" );
	BDMAC_CH_PER = XtNameToWidget ( widget121, "BDMAC_CH_PER" );
	BDMAC_CH_DAB = XtNameToWidget ( widget121, "BDMAC_CH_DAB" );
	widget131 = XtNameToWidget ( BDMAC_FM, "widget131" );
	XtAddCallback (widget131,XmNactivateCallback, XDunmanage_link, (XtPointer) &BDMAC_FM );
	widget134 = XtNameToWidget ( BDMAC_FM, "widget134" );
	BDMAC_TO_ST = XtNameToWidget ( widget134, "BDMAC_TO_ST" );
	BDMAC_TO_SD = XtNameToWidget ( widget134, "BDMAC_TO_SD" );
	BDMAC_TO_SC = XtNameToWidget ( widget134, "BDMAC_TO_SC" );
	BDMAC_TO_LT = XtNameToWidget ( widget134, "BDMAC_TO_LT" );
	BDMAC_TO_SP = XtNameToWidget ( widget134, "BDMAC_TO_SP" );
	BDMAC_TO_PCS = XtNameToWidget ( widget134, "BDMAC_TO_PCS" );
	BDMAC_TO_PC2 = XtNameToWidget ( widget134, "BDMAC_TO_PC2" );
	BDMAC_TO_PC2LT = XtNameToWidget ( widget134, "BDMAC_TO_PC2LT" );

	widget138 = XtNameToWidget ( BDMAC_FM, "widget138" );
	BDMAC_TO_OUI = XtNameToWidget ( widget138, "BDMAC_TO_OUI" );
	BDMAC_TO_NON = XtNameToWidget ( widget138, "BDMAC_TO_NON" );
	Type_Profil = XtNameToWidget ( BDMAC_FM, "Type_Profil" );
	T_PRO_NUL = XtNameToWidget ( Type_Profil, "T_PRO_NUL" );
	T_PRO_ADM = XtNameToWidget ( Type_Profil, "T_PRO_ADM" );
	T_PRO_GIT = XtNameToWidget ( Type_Profil, "T_PRO_GIT" );
	T_PRO_OTR = XtNameToWidget ( Type_Profil, "T_PRO_OTR" );

}


void create_CONFM (Display *display, char *app_name, int app_argc, char **app_argv, MrmHierarchy hierarchy_id, MrmCode *mrm_vg_class)
{
	int	cr	= 0;
	Widget children[13];      /* Children to manage */
	Arg al[64];                    /* Arg List */
	register int ac = 0;           /* Arg Count */
	XrmValue from_value, to_value; /* For resource conversion */
	XtPointer tmp_value;             /* ditto */
	int fg, bg;                    /* colour values for pixmaps */ 
	XmString *list_items;          /* For list items */
	int list_item;                 /* Index for list_items */
	Atom *atom_list;               /* For Drop Site targets */
	XmString xmstrings[16];    /* temporary storage for XmStrings */
	Widget widget143 = (Widget)NULL;
	Widget widget144 = (Widget)NULL;
	Widget widget145 = (Widget)NULL;
	Widget widget151 = (Widget)NULL;
	Widget widget152 = (Widget)NULL;
	Widget widget166 = (Widget)NULL;
	Widget widget167 = (Widget)NULL;

	XtSetArg(al[ac], XmNargc, app_argc); ac++;
	XtSetArg(al[ac], XmNargv, app_argv); ac++;

	CONFM = XtVaAppCreateShell ( app_name, "XScon", 
			applicationShellWidgetClass, 
			display, 
			XmNargc, app_argc,
			XmNargv, app_argv,
			XmNx, 0,
			XmNy, 0,NULL);
	ac = 0;
	if ((cr = MrmFetchWidget (      hierarchy_id,
					"CONFM_FM", 
					CONFM, 
					&CONFM_FM, mrm_vg_class ))
						!= MrmSUCCESS)
	{
		printf ("Erreur de fetch de la hierarchie");
	}
	else
	{
		XtManageChild ( CONFM_FM);
	}
	/*widget143 = XtNameToWidget ( CONFM_FM, "widget143" );
	widget144 = XtNameToWidget ( widget143, "widget144" );
	XtSetArg(al[ac], XmNsubMenuId, &widget145 ); ac++;
	XtGetValues(widget144, al, ac );
	ac = 0;
	widget151 = XtNameToWidget ( widget143, "widget151" );
	XtSetArg(al[ac], XmNsubMenuId, &widget152 ); ac++;
	XtGetValues(widget151, al, ac );
	ac = 0;
	widget166 = XtNameToWidget ( widget143, "widget166" );
	XtSetArg(al[ac], XmNsubMenuId, &widget167 ); ac++;
	XtGetValues(widget166, al, ac );
	ac = 0;

	XtManageChild ( CONFM_FM);*/
}



/*X*/
/*------------------------------------------------------
* SERVICE RENDU : 
*  Permet d'afficher l'inetrface Homme-Machine
------------------------------------------------------
* SEQUENCE D'APPEL :
*/

int main (int argc, char **argv)

/*
* ARGUMENTS EN ENTREE :
*
*
* ARGUMENTS EN SORTIE :
*
*
* CODE RETOUR : 
*
* CONDITION D'UTILISATION
*
* FONCTION 
*
------------------------------------------------------*/
{
	/*A
	*  initialisation semaphore
	*/
	sem_init(&vg_semaphore, 0, 1);

	MrmOsOpenParamPtr mrm_open_param = 
	   (MrmOsOpenParamPtr) XtMalloc ( sizeof ( MrmOsOpenParam ) );

	/* initialisation Mrm    */
	MrmInitialize();

/*	XtSetLanguageProc ( (XtAppContext) NULL, (XtLanguageProc) NULL, (XtPointer) NULL );*/

	/* initialisation Motif  */
	XtToolkitInitialize ();

	app_context = XtCreateApplicationContext ();
	display = XtOpenDisplay (	app_context, 
					NULL, argv[0], 	
					"XScon",
	                         	NULL, 0, 
					&argc, argv);
	if (!display)
	{
	    printf("%s: can't open display, exiting...\n", argv[0]);
	    exit (-1);
	}
	
	mrm_open_param->version = MrmOsOpenParamVersion;
	mrm_open_param->display = display;

	if ( MrmOpenHierarchy ( 1, mrm_filename_list, 
		&mrm_open_param, &vg_mrm_hierarchy ) != MrmSUCCESS )
	{
		printf("%s: can't open mrm hierarchy, exiting...\n", argv[0]);
		exit (-1);
	}

	if ( MrmRegisterNames ( reglist, reglist_num ) != MrmSUCCESS )
	{
		printf("%s: can't register mrm names, exiting...\n", argv[0]);
		exit (-1);
	}

	/* Creation des diverses boites de dialogue **/	
	create_CONFM ( display, argv[0], argc, argv, 
				vg_mrm_hierarchy, &vg_class );

	create_BDCAL ( CONFM, vg_mrm_hierarchy, &vg_class );
	create_BDSSY ( CONFM, vg_mrm_hierarchy, &vg_class );
	create_BDENT ( CONFM, vg_mrm_hierarchy, &vg_class );
	create_BDTAS ( CONFM, vg_mrm_hierarchy, &vg_class );
	create_BDSIT ( CONFM, vg_mrm_hierarchy, &vg_class );
	create_BDCON1 ( CONFM, vg_mrm_hierarchy, &vg_class );
	create_BDCON2 ( CONFM, vg_mrm_hierarchy, &vg_class );
	create_BDCJA ( CONFM, vg_mrm_hierarchy, &vg_class );
	create_BDERR ( CONFM, vg_mrm_hierarchy, &vg_class );
	create_BDCTM ( CONFM, vg_mrm_hierarchy, &vg_class );
	create_BDCMA ( CONFM, vg_mrm_hierarchy, &vg_class );
	create_BDCOMA ( CONFM, vg_mrm_hierarchy, &vg_class );
	create_BDTAC ( CONFM, vg_mrm_hierarchy, &vg_class );

	XtRealizeWidget (CONFM);

	/*  Boucle de reception des evenements X **/
	XtAppMainLoop (app_context);

	exit (0);

}	/* fin du main */


