echo "
use CFG
go
delete CFG..OPR_NOM where nom='ANDRECH'
delete CFG..OPR_NOM where nom='AUGUSTMA'
delete CFG..OPR_NOM where nom='BARDINM'
delete CFG..OPR_NOM where nom='BERTRAJC'
delete CFG..OPR_NOM where nom='BOURDIFR'
delete CFG..OPR_NOM where nom='BUSAMPC'
delete CFG..OPR_NOM where nom='CALLIGV'
delete CFG..OPR_NOM where nom='CANDELIE'
delete CFG..OPR_NOM where nom='CHIKHADM'
delete CFG..OPR_NOM where nom='CHIKHAPC'
delete CFG..OPR_NOM where nom='COMITCST'
delete CFG..OPR_NOM where nom='CROUVEZI'
delete CFG..OPR_NOM where nom='CROUVCST'
delete CFG..OPR_NOM where nom='DURANDFR'
delete CFG..OPR_NOM where nom='ESQUERIS'
delete CFG..OPR_NOM where nom='FONTANEV'
delete CFG..OPR_NOM where nom='FOURCAC'
delete CFG..OPR_NOM where nom='FRUMENT'
delete CFG..OPR_NOM where nom='GIOVANNE'
delete CFG..OPR_NOM where nom='GRINDARE'
delete CFG..OPR_NOM where nom='GUILLET'
delete CFG..OPR_NOM where nom='JEHANNRE'
delete CFG..OPR_NOM where nom='LEDRUILL'
delete CFG..OPR_NOM where nom='LEPELLET'
delete CFG..OPR_NOM where nom='MARCHIAN'
delete CFG..OPR_NOM where nom='CIMEVAER'
delete CFG..OPR_NOM where nom='MORANJ'
delete CFG..OPR_NOM where nom='NEUBERBE'
delete CFG..OPR_NOM where nom='PARISIAN'
delete CFG..OPR_NOM where nom='PRITSCHO'
delete CFG..OPR_NOM where nom='RIBREAUR'
delete CFG..OPR_NOM where nom='ROSSINVA'
delete CFG..OPR_NOM where nom='SCARFOGL'
delete CFG..OPR_NOM where nom='SINICRA'
delete CFG..OPR_NOM where nom='THIERSEL'
delete CFG..OPR_NOM where nom='VERRIEEM'
delete CFG..OPR_NOM where nom='BARKALLAH'
delete CFG..OPR_NOM where nom='ADMJPL'
delete CFG..OPR_NOM where nom='test'
go" | isql -Usa -Pzigramur -SSQL_CI