echo "
use CFG
go
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (1, 'GENERALE', 'A8', 20, 0, 1304, 515)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (2, 'UO_DP', 'A51', 20, 0, 698, 341)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (4, 'GENERALE', 'NICE', 14, 2, 1348, 577)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (5, 'GENERALE', 'MONACO', 14, 2, 1411, 529)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (6, 'GENERALE', 'AIX', 14, 2, 416, 729)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (7, 'GENERALE', 'A51', 20, 0, 745, 295)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (8, 'GENERALE', 'A52', 20, 0, 480, 809)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (9, 'GENERALE', 'A57', 20, 0, 897, 874)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (10, 'GENERALE', 'A501', 20, 0, 469, 853)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (11, 'GENERALE', 'A50', 20, 0, 612, 903)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (12, 'GENERALE', 'A500', 20, 0, 1469, 523)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (13, 'GENERALE', 'A520', 20, 0, 578, 805)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (16, 'UO_DP', 'A8', 20, 0, 1577, 402)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (18, 'UO_DP', 'A520', 20, 0, 1358, 507)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (19, 'UO_DP', 'A501', 20, 0, 1228, 606)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (20, 'UO_DP', 'A52', 20, 0, 1227, 452)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (21, 'UO_DP', 'A50', 20, 0, 1438, 697)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (22, 'UO_VC', 'A8', 20, 0, 1065, 503)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (23, 'UO_VC', 'A500', 20, 0, 1555, 299)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (24, 'UO_VC', 'A57', 20, 0, 655, 855)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (28, 'GENERALE', 'GAP', 14, 1, 720, 7)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (29, 'GENERALE', 'MARSEILLE', 14, 2, 402, 862)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (30, 'GENERALE', 'TOULON', 14, 2, 753, 984)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (31, 'GENERALE', 'VINTIMILLE', 14, 2, 1560, 464)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (32, 'GENERALE', 'ANTIBES', 14, 2, 1300, 639)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (47, 'GENERALE', 'A8', 20, 0, 678, 718)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (48, 'GENERALE', 'La Barque', 10, 0, 467, 748)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (49, 'GENERALE', 'Meyrargues', 10, 0, 525, 628)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (50, 'GENERALE', 'La Saulce', 10, 0, 752, 38)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (51, 'GENERALE', 'Auriol', 10, 0, 571, 825)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (52, 'GENERALE', 'Pont de l''Etoile', 10, 0, 563, 857)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (53, 'GENERALE', 'La Ciotat', 10, 0, 531, 953)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (54, 'GENERALE', 'Bandol', 10, 0, 635, 1001)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (55, 'GENERALE', 'Puget Ville', 10, 0, 840, 891)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (56, 'GENERALE', 'Capitou', 10, 0, 1125, 734)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (57, 'GENERALE', 'Antibes', 10, 0, 1254, 589)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (58, 'GENERALE', 'Nice St Isidore', 10, 0, 1280, 553)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (59, 'GENERALE', 'La Turbie', 10, 0, 1402, 484)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (60, 'GENERALE', 'Monaco', 10, 0, 1468, 507)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (61, 'UO_DP', 'La Saulce', 10, 0, 689, 75)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (62, 'UO_DP', 'Meyrargues', 10, 0, 430, 923)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (63, 'UO_DP', 'La Barque', 10, 0, 1209, 404)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (64, 'UO_DP', 'Auriol', 10, 0, 1351, 530)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (65, 'UO_DP', 'Pont de l''Etoile', 10, 0, 1331, 583)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (66, 'UO_DP', 'La Ciotat', 10, 0, 1312, 752)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (67, 'UO_DP', 'Bandol', 10, 0, 1442, 807)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (68, 'UO_VC', 'Puget Ville', 10, 0, 492, 869)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (69, 'UO_VC', 'Capitou', 10, 0, 1000, 577)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (70, 'UO_VC', 'Antibes', 10, 0, 1315, 399)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (71, 'UO_VC', 'Nice St Isidore', 10, 0, 1390, 277)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (72, 'UO_VC', 'Monaco', 10, 0, 1593, 276)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (73, 'UO_VC', 'La Turbie', 10, 0, 1649, 259)
INSERT INTO SYN_LIB_FLT (numero, type_synoptique, texte, taille, epingle, x, y) VALUES (74, 'UO_DP', 'A57', 20, 0, 1854, 621)
go" | isql -Usa -Pzigramur -SSQL_CI