../sub_create.rab EXP FMC_VEH DP DS xx fmc_veh.lis
../sub_create.rab EXP FMC_VEH DS DP xx fmc_veh.lis
../sub_create.rab EXP FMC_VEH DP CI xx fmc_veh.lis
../sub_create.rab HIS FMC_VEH DP HIS xx fmc_veh.lis
../sub_create.rab EXP FMC_VEH DS DC xx fmc_veh.lis
../sub_create.rab EXP FMC_VEH DC DS xx fmc_veh.lis
../sub_create.rab EXP FMC_VEH DS CI xx fmc_veh.lis
../sub_create.rab HIS FMC_VEH DS HIS xx fmc_veh.lis
../sub_create.rab EXP FMC_VEH DC DM xx fmc_veh.lis
../sub_create.rab EXP FMC_VEH DM DC xx fmc_veh.lis
../sub_create.rab EXP FMC_VEH DC CI xx fmc_veh.lis
../sub_create.rab HIS FMC_VEH DC HIS xx fmc_veh.lis
../sub_create.rab EXP FMC_VEH DM CI xx fmc_veh.lis
../sub_create.rab HIS FMC_VEH DM HIS xx fmc_veh.lis
../sub_create.rab EXP FMC_VEH CI DP xx fmc_veh.lis
../sub_create.rab EXP FMC_VEH CI DS xx fmc_veh.lis
../sub_create.rab EXP FMC_VEH CI DC xx fmc_veh.lis
../sub_create.rab EXP FMC_VEH CI DM xx fmc_veh.lis
../sub_create.rab HIS FMC_VEH CI HIS xx fmc_veh.lis
